In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('dataset_linux_driver_net.csv')
df2 = pd.read_csv('dataset_linux_driver_scsi.csv')
df3 = pd.read_csv('dataset_linux_ext3.csv')
df4 = pd.read_csv('dataset_linux_ipv4.csv')
df5 = pd.read_csv('dataset_mysql_innodb.csv')
df6 = pd.read_csv('dataset_mysql_optimizer.csv')
df7 = pd.read_csv('dataset_mysql_replication.csv')

df = pd.concat([df1, df2, df3, df4, df5, df6, df7])
df

,id,Filename,AltAvgLineBlank,AltAvgLineCode,AltAvgLineComment,AltCountLineBlank,AltCountLineCode,AltCountLineComment,AvgCyclomatic,AvgCyclomaticModified,...,Vol,Dif,Eff,AllocOps,DeallocOps,DerefUse,UniqueDerefUse,DerefSet,UniqueDerefSet,AgingRelatedBugs
0,1,drivers/net/3c501.c,6.00,27.82,9.42,129.89,445.95,377.26,5.00,5.00,...,11479.39,186.29,289423.61,0.07,0.07,73.95,19.07,25.75,9.60,0
1,2,drivers/net/3c501.h,0.00,0.00,0.00,17.00,59.24,35.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
2,3,drivers/net/3c503.c,4.79,35.61,7.58,90.05,529.74,152.68,6.58,6.58,...,14708.61,279.63,594338.34,0.00,0.07,102.85,18.32,16.27,6.05,0
3,4,drivers/net/3c503.h,0.00,0.00,0.00,16.00,44.00,68.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,5,drivers/net/3c505.c,4.00,28.66,6.00,225.50,1038.03,441.71,6.74,6.00,...,37936.53,638.55,1667451.55,0.07,1.07,337.50,53.25,117.70,23.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,28,sql/slave.h,0.00,0.00,0.00,30.00,92.36,107.75,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
28,29,sql/sql_class.cc,1.00,14.00,2.00,463.93,2586.50,923.46,2.64,2.64,...,56432.89,1464.25,1278159.46,17.00,8.00,68.39,31.25,14.36,10.36,1
29,30,sql/sql_class.h,0.00,2.00,0.00,297.93,1653.79,1183.68,1.00,1.00,...,1255.00,72.00,7813.00,5.00,1.00,0.00,0.00,0.00,0.00,0
30,31,sql/sql_lex.cc,1.00,21.00,4.00,300.82,1889.57,924.00,4.00,3.00,...,54895.25,1048.25,3633694.18,2.00,2.00,336.75,25.82,141.29,13.29,0
31,32,sql/sql_lex.h,0.00,0.00,0.00,221.07,1037.04,792.96,0.00,0.00,...,0.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00,0

In [3]:
df.drop(['id','Filename'], axis = 1, inplace=True)
df

,AltAvgLineBlank,AltAvgLineCode,AltAvgLineComment,AltCountLineBlank,AltCountLineCode,AltCountLineComment,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,...,Vol,Dif,Eff,AllocOps,DeallocOps,DerefUse,UniqueDerefUse,DerefSet,UniqueDerefSet,AgingRelatedBugs
0,6.00,27.82,9.42,129.89,445.95,377.26,5.00,5.00,5.50,2.00,...,11479.39,186.29,289423.61,0.07,0.07,73.95,19.07,25.75,9.60,0
1,0.00,0.00,0.00,17.00,59.24,35.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
2,4.79,35.61,7.58,90.05,529.74,152.68,6.58,6.58,7.00,3.71,...,14708.61,279.63,594338.34,0.00,0.07,102.85,18.32,16.27,6.05,0
3,0.00,0.00,0.00,16.00,44.00,68.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,4.00,28.66,6.00,225.50,1038.03,441.71,6.74,6.00,7.74,2.74,...,37936.53,638.55,1667451.55,0.07,1.07,337.50,53.25,117.70,23.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,0.00,0.00,0.00,30.00,92.36,107.75,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
28,1.00,14.00,2.00,463.93,2586.50,923.46,2.64,2.64,3.11,1.00,...,56432.89,1464.25,1278159.46,17.00,8.00,68.39,31.25,14.36,10.36,1
29,0.00,2.00,0.00,297.93,1653.79,1183.68,1.00,1.00,1.00,1.00,...,1255.00,72.00,7813.00,5.00,1.00,0.00,0.00,0.00,0.00,0
30,1.00,21.00,4.00,300.82,1889.57,924.00,4.00,3.00,5.00,2.00,...,54895.25,1048.25,3633694.18,2.00,2.00,336.75,25.82,141.29,13.29,0
31,0.00,0.00,0.00,221.07,1037.04,792.96,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00,0

In [4]:
df = df.rename({'AgingRelatedBugs':'class'}, axis=1)
df

,AltAvgLineBlank,AltAvgLineCode,AltAvgLineComment,AltCountLineBlank,AltCountLineCode,AltCountLineComment,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,...,Vol,Dif,Eff,AllocOps,DeallocOps,DerefUse,UniqueDerefUse,DerefSet,UniqueDerefSet,class
0,6.00,27.82,9.42,129.89,445.95,377.26,5.00,5.00,5.50,2.00,...,11479.39,186.29,289423.61,0.07,0.07,73.95,19.07,25.75,9.60,0
1,0.00,0.00,0.00,17.00,59.24,35.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
2,4.79,35.61,7.58,90.05,529.74,152.68,6.58,6.58,7.00,3.71,...,14708.61,279.63,594338.34,0.00,0.07,102.85,18.32,16.27,6.05,0
3,0.00,0.00,0.00,16.00,44.00,68.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,4.00,28.66,6.00,225.50,1038.03,441.71,6.74,6.00,7.74,2.74,...,37936.53,638.55,1667451.55,0.07,1.07,337.50,53.25,117.70,23.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,0.00,0.00,0.00,30.00,92.36,107.75,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
28,1.00,14.00,2.00,463.93,2586.50,923.46,2.64,2.64,3.11,1.00,...,56432.89,1464.25,1278159.46,17.00,8.00,68.39,31.25,14.36,10.36,1
29,0.00,2.00,0.00,297.93,1653.79,1183.68,1.00,1.00,1.00,1.00,...,1255.00,72.00,7813.00,5.00,1.00,0.00,0.00,0.00,0.00,0
30,1.00,21.00,4.00,300.82,1889.57,924.00,4.00,3.00,5.00,2.00,...,54895.25,1048.25,3633694.18,2.00,2.00,336.75,25.82,141.29,13.29,0
31,0.00,0.00,0.00,221.07,1037.04,792.96,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00,0

In [5]:
df = df.reset_index(drop=True)
df

,AltAvgLineBlank,AltAvgLineCode,AltAvgLineComment,AltCountLineBlank,AltCountLineCode,AltCountLineComment,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,...,Vol,Dif,Eff,AllocOps,DeallocOps,DerefUse,UniqueDerefUse,DerefSet,UniqueDerefSet,class
0,6.00,27.82,9.42,129.89,445.95,377.26,5.00,5.00,5.50,2.00,...,11479.39,186.29,289423.61,0.07,0.07,73.95,19.07,25.75,9.60,0
1,0.00,0.00,0.00,17.00,59.24,35.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
2,4.79,35.61,7.58,90.05,529.74,152.68,6.58,6.58,7.00,3.71,...,14708.61,279.63,594338.34,0.00,0.07,102.85,18.32,16.27,6.05,0
3,0.00,0.00,0.00,16.00,44.00,68.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,4.00,28.66,6.00,225.50,1038.03,441.71,6.74,6.00,7.74,2.74,...,37936.53,638.55,1667451.55,0.07,1.07,337.50,53.25,117.70,23.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,0.00,0.00,0.00,30.00,92.36,107.75,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
3866,1.00,14.00,2.00,463.93,2586.50,923.46,2.64,2.64,3.11,1.00,...,56432.89,1464.25,1278159.46,17.00,8.00,68.39,31.25,14.36,10.36,1
3867,0.00,2.00,0.00,297.93,1653.79,1183.68,1.00,1.00,1.00,1.00,...,1255.00,72.00,7813.00,5.00,1.00,0.00,0.00,0.00,0.00,0
3868,1.00,21.00,4.00,300.82,1889.57,924.00,4.00,3.00,5.00,2.00,...,54895.25,1048.25,3633694.18,2.00,2.00,336.75,25.82,141.29,13.29,0
3869,0.00,0.00,0.00,221.07,1037.04,792.96,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00,0

In [6]:
X = df.drop(['class'], axis=1)
X

,AltAvgLineBlank,AltAvgLineCode,AltAvgLineComment,AltCountLineBlank,AltCountLineCode,AltCountLineComment,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,...,Voc,Vol,Dif,Eff,AllocOps,DeallocOps,DerefUse,UniqueDerefUse,DerefSet,UniqueDerefSet
0,6.00,27.82,9.42,129.89,445.95,377.26,5.00,5.00,5.50,2.00,...,629.63,11479.39,186.29,289423.61,0.07,0.07,73.95,19.07,25.75,9.60
1,0.00,0.00,0.00,17.00,59.24,35.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,4.79,35.61,7.58,90.05,529.74,152.68,6.58,6.58,7.00,3.71,...,684.29,14708.61,279.63,594338.34,0.00,0.07,102.85,18.32,16.27,6.05
3,0.00,0.00,0.00,16.00,44.00,68.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,4.00,28.66,6.00,225.50,1038.03,441.71,6.74,6.00,7.74,2.74,...,1624.97,37936.53,638.55,1667451.55,0.07,1.07,337.50,53.25,117.70,23.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,0.00,0.00,0.00,30.00,92.36,107.75,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3866,1.00,14.00,2.00,463.93,2586.50,923.46,2.64,2.64,3.11,1.00,...,4137.32,56432.89,1464.25,1278159.46,17.00,8.00,68.39,31.25,14.36,10.36
3867,0.00,2.00,0.00,297.93,1653.79,1183.68,1.00,1.00,1.00,1.00,...,199.00,1255.00,72.00,7813.00,5.00,1.00,0.00,0.00,0.00,0.00
3868,1.00,21.00,4.00,300.82,1889.57,924.00,4.00,3.00,5.00,2.00,...,2471.75,54895.25,1048.25,3633694.18,2.00,2.00,336.75,25.82,141.29,13.29
3869,0.00,0.00,0.00,221.07,1037.04,792.96,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00

In [7]:
Y = df['class']
Y

0       0
1       0
2       0
3       0
4       0
       ..
3865    0
3866    1
3867    0
3868    0
3869    0
Name: class, Length: 3870, dtype: int64

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *

# All Features

In [15]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X, Y, scoring='roc_auc', cv=cv, n_jobs=-1)

In [16]:
scores

array([0.5287844 , 0.67408759, 0.6558011 , 0.72379647, 0.56464088,
       0.5806781 , 0.55898168])

In [17]:
scores.mean()

0.6123957482509207

# PEARSON CORRELATION

In [22]:
cor = df.corr()
cor_target = abs(cor['class'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.2]
relevant_features

AltCountLineBlank      0.238590
AltCountLineComment    0.219970
CountLine              0.203172
CountLineBlank         0.227132
CountLineComment       0.208169
class                  1.000000
Name: class, dtype: float64

In [24]:
X_new = df[['AltCountLineBlank', 'AltCountLineComment', 'CountLine', 'CountLineBlank', 'CountLineComment']]
X_new

,AltCountLineBlank,AltCountLineComment,CountLine,CountLineBlank,CountLineComment
0,129.89,377.26,923.53,122.66,359.71
1,17.00,35.00,92.24,17.00,35.00
2,90.05,152.68,743.53,84.42,141.89
3,16.00,68.00,91.00,16.00,68.00
4,225.50,441.71,1684.68,219.58,441.71
...,...,...,...,...,...
3865,30.00,107.75,226.36,30.00,107.75
3866,463.93,923.46,3917.39,395.07,716.89
3867,297.93,1183.68,3051.07,55.50,142.18
3868,300.82,924.00,2996.64,300.82,923.71
3869,221.07,792.96,1993.07,11.00,39.00

In [28]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.53256881, 0.67062044, 0.72559853, 0.72501523, 0.62707182,
       0.47610294, 0.56469501])

In [29]:
scores.mean()

0.6173818257478897

# INFORMATION GAIN 10

In [30]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([1.06875273e-02, 7.82006952e-03, 1.15972190e-02, 1.39010188e-02,
       1.07036675e-02, 1.58887509e-02, 7.31053734e-03, 7.18981453e-03,
       1.05778175e-02, 3.48050494e-03, 1.07550737e-02, 8.61605918e-03,
       7.92657997e-03, 1.44356465e-02, 2.95943243e-03, 1.90856452e-03,
       4.59102391e-04, 1.92416590e-03, 1.48571892e-03, 0.00000000e+00,
       6.92039885e-03, 2.08859812e-03, 9.49673620e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.89530734e-04, 0.00000000e+00,
       0.00000000e+00, 1.94401294e-03, 0.00000000e+00, 8.42161459e-04,
       0.00000000e+00, 0.00000000e+00, 1.38917593e-02, 1.30684096e-02,
       1.62485388e-02, 1.04343395e-02, 9.62485530e-03, 1.35302842e-02,
       8.56873770e-03, 2.56862418e-03, 1.32007313e-03, 0.00000000e+00,
       1.32509955e-02, 1.14868285e-02, 8.22747801e-03, 1.07838767e-02,
       1.12256892e-02, 5.31969855e-03, 2.85963620e-03, 1.79497186e-03,
       1.37492879e-03, 1.39699923e-03, 9.20242328e-03, 1.08767852e-02,
       9.88718771e-03, 1.85030685e-03, 2.43529128e-05, 0.00000000e+00,
       0.00000000e+00, 1.14146762e-03, 1.03588198e-02, 1.26212471e-02,
       1.25213709e-02, 7.71250104e-03, 1.21767985e-02, 6.19415783e-03,
       9.52608319e-03, 1.04015901e-02, 1.06856998e-02, 1.17764451e-02,
       1.10610913e-02, 9.14171583e-03, 8.67305615e-03, 1.11075776e-02,
       4.18486501e-03, 7.36866827e-04, 5.12652568e-03, 9.39366145e-03,
       6.42214817e-03, 7.00593189e-03])

In [31]:
col_list = X.columns
col_list

Index(['AltAvgLineBlank', 'AltAvgLineCode', 'AltAvgLineComment',
       'AltCountLineBlank', 'AltCountLineCode', 'AltCountLineComment',
       'AvgCyclomatic', 'AvgCyclomaticModified', 'AvgCyclomaticStrict',
       'AvgEssential', 'AvgLine', 'AvgLineBlank', 'AvgLineCode',
       'AvgLineComment', 'CountClassBase', 'CountClassCoupled',
       'CountClassDerived', 'CountDeclClass', 'CountDeclClassMethod',
       'CountDeclClassVariable', 'CountDeclFunction',
       'CountDeclInstanceMethod', 'CountDeclInstanceVariable',
       'CountDeclInstanceVariablePrivate',
       'CountDeclInstanceVariableProtected', 'CountDeclInstanceVariablePublic',
       'CountDeclMethod', 'CountDeclMethodAll', 'CountDeclMethodConst',
       'CountDeclMethodFriend', 'CountDeclMethodPrivate',
       'CountDeclMethodProtected', 'CountDeclMethodPublic', 'CountInput',
       'CountLine', 'CountLineBlank', 'CountLineCode', 'CountLineCodeDecl',
       'CountLineCodeExe', 'CountLineComment', 'CountLineInactive',
       'CountLinePreprocessor', 'CountOutput', 'CountPath', 'CountSemicolon',
       'CountStmt', 'CountStmtDecl', 'CountStmtEmpty', 'CountStmtExe',
       'Cyclomatic', 'CyclomaticModified', 'CyclomaticStrict', 'Essential',
       'Knots', 'MaxCyclomatic', 'MaxCyclomaticModified',
       'MaxCyclomaticStrict', 'MaxEssentialKnots', 'MaxInheritanceTree',
       'MaxNesting', 'MinEssentialKnots', 'PercentLackOfCohesion',
       'RatioCommentToCode', 'SumCyclomatic', 'SumCyclomaticModified',
       'SumCyclomaticStrict', 'SumEssential', 'n1', 'n2', 'N1', 'N2', 'Len',
       'Voc', 'Vol', 'Dif', 'Eff', 'AllocOps', 'DeallocOps', 'DerefUse',
       'UniqueDerefUse', 'DerefSet', 'UniqueDerefSet'],
      dtype='object')

In [32]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

                  col     score
0     AltAvgLineBlank  0.010688
1      AltAvgLineCode  0.007820
2   AltAvgLineComment  0.011597
3   AltCountLineBlank  0.013901
4    AltCountLineCode  0.010704
..                ...       ...
77         DeallocOps  0.000737
78           DerefUse  0.005127
79     UniqueDerefUse  0.009394
80           DerefSet  0.006422
81     UniqueDerefSet  0.007006

[82 rows x 2 columns]

In [33]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

                      col     score
36          CountLineCode  0.016249
5     AltCountLineComment  0.015889
13         AvgLineComment  0.014436
3       AltCountLineBlank  0.013901
34              CountLine  0.013892
39       CountLineComment  0.013530
44         CountSemicolon  0.013251
35         CountLineBlank  0.013068
63          SumCyclomatic  0.012621
64  SumCyclomaticModified  0.012521

In [34]:
FS = list(temp_sort['col'][:10])
FS

['CountLineCode',
 'AltCountLineComment',
 'AvgLineComment',
 'AltCountLineBlank',
 'CountLine',
 'CountLineComment',
 'CountSemicolon',
 'CountLineBlank',
 'SumCyclomatic',
 'SumCyclomaticModified']

In [35]:
X_new = df[FS]
X_new

,CountLineCode,AltCountLineComment,AvgLineComment,AltCountLineBlank,CountLine,CountLineComment,CountSemicolon,CountLineBlank,SumCyclomatic,SumCyclomaticModified
0,400.11,377.26,9.42,129.89,923.53,359.71,238.89,122.66,62.82,62.82
1,20.24,35.00,0.00,17.00,92.24,35.00,18.24,17.00,0.00,0.00
2,415.74,152.68,7.58,90.05,743.53,141.89,248.08,84.42,73.68,73.68
3,0.00,68.00,0.00,16.00,91.00,68.00,0.00,16.00,0.00,0.00
4,937.45,441.71,6.00,225.50,1684.68,441.71,558.95,219.58,207.03,193.03
...,...,...,...,...,...,...,...,...,...,...
3865,71.36,107.75,0.00,30.00,226.36,107.75,55.96,30.00,0.00,0.00
3866,2009.64,923.46,2.00,463.93,3917.39,716.89,1079.39,395.07,391.89,387.89
3867,283.07,1183.68,0.00,297.93,3051.07,142.18,218.64,55.50,14.00,14.00
3868,1798.50,924.00,4.00,300.82,2996.64,923.71,869.46,300.82,377.71,302.71
3869,66.00,792.96,0.00,221.07,1993.07,39.00,11.00,11.00,0.00,0.00

In [36]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.65917431, 0.76551095, 0.71786372, 0.72973796, 0.72661142,
       0.47426471, 0.51924046])

In [37]:
scores.mean()

0.6560576476112729

# INFORMATION GAIN 15

In [38]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.01134453, 0.00852089, 0.01473507, 0.01381435, 0.01070321,
       0.01580116, 0.00805041, 0.00819063, 0.0100935 , 0.00406052,
       0.00992328, 0.00749736, 0.00827814, 0.01398981, 0.        ,
       0.00327602, 0.0035207 , 0.        , 0.        , 0.00034793,
       0.00638325, 0.00101296, 0.00095279, 0.0005635 , 0.00328041,
       0.        , 0.00103291, 0.        , 0.        , 0.00262936,
       0.        , 0.00281241, 0.0038596 , 0.        , 0.01406221,
       0.01317863, 0.01641247, 0.01009282, 0.00859255, 0.0134623 ,
       0.01005929, 0.00325725, 0.00078949, 0.00105026, 0.013251  ,
       0.01184328, 0.00745774, 0.0128317 , 0.0111432 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00927262,
       0.01021495, 0.0096281 , 0.00268879, 0.00238461, 0.00322912,
       0.        , 0.        , 0.00879024, 0.01232856, 0.01301302,
       0.00810841, 0.01156748, 0.00612361, 0.00908384, 0.01030632,
       0.0105765 , 0.01116393, 0.01160862, 0.00854146, 0.00893564,
       0.01047674, 0.        , 0.00349036, 0.00549275, 0.01003983,
       0.0065369 , 0.00645938])

In [39]:
col_list = X.columns
col_list

Index(['AltAvgLineBlank', 'AltAvgLineCode', 'AltAvgLineComment',
       'AltCountLineBlank', 'AltCountLineCode', 'AltCountLineComment',
       'AvgCyclomatic', 'AvgCyclomaticModified', 'AvgCyclomaticStrict',
       'AvgEssential', 'AvgLine', 'AvgLineBlank', 'AvgLineCode',
       'AvgLineComment', 'CountClassBase', 'CountClassCoupled',
       'CountClassDerived', 'CountDeclClass', 'CountDeclClassMethod',
       'CountDeclClassVariable', 'CountDeclFunction',
       'CountDeclInstanceMethod', 'CountDeclInstanceVariable',
       'CountDeclInstanceVariablePrivate',
       'CountDeclInstanceVariableProtected', 'CountDeclInstanceVariablePublic',
       'CountDeclMethod', 'CountDeclMethodAll', 'CountDeclMethodConst',
       'CountDeclMethodFriend', 'CountDeclMethodPrivate',
       'CountDeclMethodProtected', 'CountDeclMethodPublic', 'CountInput',
       'CountLine', 'CountLineBlank', 'CountLineCode', 'CountLineCodeDecl',
       'CountLineCodeExe', 'CountLineComment', 'CountLineInactive',
       'CountLinePreprocessor', 'CountOutput', 'CountPath', 'CountSemicolon',
       'CountStmt', 'CountStmtDecl', 'CountStmtEmpty', 'CountStmtExe',
       'Cyclomatic', 'CyclomaticModified', 'CyclomaticStrict', 'Essential',
       'Knots', 'MaxCyclomatic', 'MaxCyclomaticModified',
       'MaxCyclomaticStrict', 'MaxEssentialKnots', 'MaxInheritanceTree',
       'MaxNesting', 'MinEssentialKnots', 'PercentLackOfCohesion',
       'RatioCommentToCode', 'SumCyclomatic', 'SumCyclomaticModified',
       'SumCyclomaticStrict', 'SumEssential', 'n1', 'n2', 'N1', 'N2', 'Len',
       'Voc', 'Vol', 'Dif', 'Eff', 'AllocOps', 'DeallocOps', 'DerefUse',
       'UniqueDerefUse', 'DerefSet', 'UniqueDerefSet'],
      dtype='object')

In [40]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

                  col     score
0     AltAvgLineBlank  0.011345
1      AltAvgLineCode  0.008521
2   AltAvgLineComment  0.014735
3   AltCountLineBlank  0.013814
4    AltCountLineCode  0.010703
..                ...       ...
77         DeallocOps  0.003490
78           DerefUse  0.005493
79     UniqueDerefUse  0.010040
80           DerefSet  0.006537
81     UniqueDerefSet  0.006459

[82 rows x 2 columns]

In [41]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:15]

                      col     score
36          CountLineCode  0.016412
5     AltCountLineComment  0.015801
2       AltAvgLineComment  0.014735
34              CountLine  0.014062
13         AvgLineComment  0.013990
3       AltCountLineBlank  0.013814
39       CountLineComment  0.013462
44         CountSemicolon  0.013251
35         CountLineBlank  0.013179
64  SumCyclomaticModified  0.013013
47         CountStmtEmpty  0.012832
63          SumCyclomatic  0.012329
45              CountStmt  0.011843
72                    Voc  0.011609
66           SumEssential  0.011567

In [42]:
FS = list(temp_sort['col'][:15])
FS

['CountLineCode',
 'AltCountLineComment',
 'AltAvgLineComment',
 'CountLine',
 'AvgLineComment',
 'AltCountLineBlank',
 'CountLineComment',
 'CountSemicolon',
 'CountLineBlank',
 'SumCyclomaticModified',
 'CountStmtEmpty',
 'SumCyclomatic',
 'CountStmt',
 'Voc',
 'SumEssential']

In [43]:
X_new = df[FS]
X_new

,CountLineCode,AltCountLineComment,AltAvgLineComment,CountLine,AvgLineComment,AltCountLineBlank,CountLineComment,CountSemicolon,CountLineBlank,SumCyclomaticModified,CountStmtEmpty,SumCyclomatic,CountStmt,Voc,SumEssential
0,400.11,377.26,9.42,923.53,9.42,129.89,359.71,238.89,122.66,62.82,0.00,62.82,327.26,629.63,27.05
1,20.24,35.00,0.00,92.24,0.00,17.00,35.00,18.24,17.00,0.00,0.00,0.00,18.24,0.00,0.00
2,415.74,152.68,7.58,743.53,7.58,90.05,141.89,248.08,84.42,73.68,9.00,73.68,317.32,684.29,46.50
3,0.00,68.00,0.00,91.00,0.00,16.00,68.00,0.00,16.00,0.00,0.00,0.00,0.00,0.00,0.00
4,937.45,441.71,6.00,1684.68,6.00,225.50,441.71,558.95,219.58,193.03,13.71,207.03,770.32,1624.97,96.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,71.36,107.75,0.00,226.36,0.00,30.00,107.75,55.96,30.00,0.00,0.00,0.00,55.96,0.00,0.00
3866,2009.64,923.46,2.00,3917.39,2.00,463.93,716.89,1079.39,395.07,387.89,5.57,391.89,1435.93,4137.32,219.79
3867,283.07,1183.68,0.00,3051.07,0.00,297.93,142.18,218.64,55.50,14.00,0.00,14.00,239.64,199.00,14.00
3868,1798.50,924.00,4.00,2996.64,4.00,300.82,923.71,869.46,300.82,302.71,28.00,377.71,1245.54,2471.75,210.14
3869,66.00,792.96,0.00,1993.07,0.00,221.07,39.00,11.00,11.00,0.00,0.00,0.00,11.00,0.00,0.00

In [44]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.64529817, 0.6669708 , 0.77403315, 0.71739793, 0.76998158,
       0.58843954, 0.47319778])

In [45]:
scores.mean()

0.6621884219262879

# FISHER SCORE

In [46]:
FScore = []

for m in  range(len(col_list)):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        FScore.append(inter_class / intra_class)

FScore

C:\Users\acer\AppData\Local\Temp\ipykernel_9028\1507033413.py:17: RuntimeWarning: invalid value encountered in double_scalars
  FScore.append(inter_class / intra_class)

[0.016106831172497962,
 0.009825016332923748,
 0.020325095760278685,
 0.06036114100547917,
 0.029400665824350327,
 0.0508472546023781,
 0.0004911273784637394,
 0.00047584178557400446,
 0.0002301640657195956,
 0.0048141231605520664,
 0.012663963869552732,
 0.015153289911493156,
 0.009274046942087668,
 0.019877446649437674,
 nan,
 nan,
 nan,
 3.1545876447640956e-06,
 nan,
 nan,
 0.024767755682832567,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.04305634757417372,
 0.05439506513804271,
 0.025333411081260398,
 0.0019153352476850823,
 0.017677878098300605,
 0.04529746586287174,
 0.02123768922285927,
 7.150821566894593e-05,
 nan,
 nan,
 0.030942948478032615,
 0.03412814895071864,
 0.017995592356178175,
 0.0024980672754580597,
 0.03596509373227452,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0025887002740013817,
 0.0020254621114164867,
 0.001399393356330795,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0003748737219026618,
 0.018162678449218938,
 0.017277718512165485,
 0.011460425162145144,
 0.03615233102574324,
 0.026734841055856183,
 0.02890641008699079,
 0.020105362493934745,
 0.01947524792646542,
 0.01983871503818502,
 0.029042708282026448,
 0.013600171948736818,
 0.02613244307851074,
 0.001752874212752073,
 0.00822296666300944,
 0.004472829088987547,
 0.012987888299870746,
 0.01435455237296807,
 0.009297255928021308,
 0.019408374068367543]

In [47]:
temp = pd.DataFrame(list(zip(col_list, FScore)), columns =['col', 'score']) 
temp

                  col     score
0     AltAvgLineBlank  0.016107
1      AltAvgLineCode  0.009825
2   AltAvgLineComment  0.020325
3   AltCountLineBlank  0.060361
4    AltCountLineCode  0.029401
..                ...       ...
77         DeallocOps  0.004473
78           DerefUse  0.012988
79     UniqueDerefUse  0.014355
80           DerefSet  0.009297
81     UniqueDerefSet  0.019408

[82 rows x 2 columns]

In [48]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

                    col     score
3     AltCountLineBlank  0.060361
35       CountLineBlank  0.054395
5   AltCountLineComment  0.050847
39     CountLineComment  0.045297
34            CountLine  0.043056
66         SumEssential  0.036152
48         CountStmtExe  0.035965
45            CountStmt  0.034128
44       CountSemicolon  0.030943
4      AltCountLineCode  0.029401

In [49]:
FS = list(temp_sort['col'][:10])
FS

['AltCountLineBlank',
 'CountLineBlank',
 'AltCountLineComment',
 'CountLineComment',
 'CountLine',
 'SumEssential',
 'CountStmtExe',
 'CountStmt',
 'CountSemicolon',
 'AltCountLineCode']

In [50]:
X_new = df[FS]
X_new

,AltCountLineBlank,CountLineBlank,AltCountLineComment,CountLineComment,CountLine,SumEssential,CountStmtExe,CountStmt,CountSemicolon,AltCountLineCode
0,129.89,122.66,377.26,359.71,923.53,27.05,221.95,327.26,238.89,445.95
1,17.00,17.00,35.00,35.00,92.24,0.00,0.00,18.24,18.24,59.24
2,90.05,84.42,152.68,141.89,743.53,46.50,235.74,317.32,248.08,529.74
3,16.00,16.00,68.00,68.00,91.00,0.00,0.00,0.00,0.00,44.00
4,225.50,219.58,441.71,441.71,1684.68,96.05,625.66,770.32,558.95,1038.03
...,...,...,...,...,...,...,...,...,...,...
3865,30.00,30.00,107.75,107.75,226.36,0.00,0.00,55.96,55.96,92.36
3866,463.93,395.07,923.46,716.89,3917.39,219.79,1077.43,1435.93,1079.39,2586.50
3867,297.93,55.50,1183.68,142.18,3051.07,14.00,7.00,239.64,218.64,1653.79
3868,300.82,300.82,924.00,923.71,2996.64,210.14,1048.93,1245.54,869.46,1889.57
3869,221.07,11.00,792.96,39.00,1993.07,0.00,0.00,11.00,11.00,1037.04

In [51]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.6603211 , 0.6649635 , 0.62596685, 0.6496039 , 0.62025783,
       0.52777778, 0.52226517])

In [52]:
scores.mean()

0.6101651608057962

# SVM RFE 10

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [54]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=10)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [59]:
X_new = X.loc[:, rfe.support_]
X_new

,AltAvgLineComment,AltCountLineBlank,AltCountLineComment,CountLine,CountLineBlank,SumCyclomaticModified,Len,Eff,DerefUse,DerefSet
0,9.42,129.89,377.26,923.53,122.66,62.82,1855.11,289423.61,73.95,25.75
1,0.00,17.00,35.00,92.24,17.00,0.00,0.00,0.00,0.00,0.00
2,7.58,90.05,152.68,743.53,84.42,73.68,2287.26,594338.34,102.85,16.27
3,0.00,16.00,68.00,91.00,16.00,0.00,0.00,0.00,0.00,0.00
4,6.00,225.50,441.71,1684.68,219.58,193.03,5864.24,1667451.55,337.50,117.70
...,...,...,...,...,...,...,...,...,...,...
3865,0.00,30.00,107.75,226.36,30.00,0.00,0.00,0.00,0.00,0.00
3866,2.00,463.93,923.46,3917.39,395.07,387.89,10313.93,1278159.46,68.39,14.36
3867,0.00,297.93,1183.68,3051.07,55.50,14.00,308.00,7813.00,0.00,0.00
3868,4.00,300.82,924.00,2996.64,300.82,302.71,8994.04,3633694.18,336.75,141.29
3869,0.00,221.07,792.96,1993.07,11.00,0.00,0.00,0.00,0.00,0.00

In [60]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.46513761, 0.66423358, 0.60718232, 0.79494211, 0.57034991,
       0.69526144, 0.55772139])

In [61]:
scores.mean()

0.6221183367748472

# SVM RFE 15

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [63]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=15)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [64]:
X_new = X.loc[:, rfe.support_]
X_new

,AltCountLineBlank,AltCountLineComment,AvgLineBlank,AvgLineComment,CountLineBlank,CountLineComment,CountLineInactive,CountSemicolon,SumCyclomatic,SumCyclomaticModified,Len,Vol,Eff,DerefUse,DerefSet
0,129.89,377.26,6.00,9.42,122.66,359.71,45.26,238.89,62.82,62.82,1855.11,11479.39,289423.61,73.95,25.75
1,17.00,35.00,0.00,0.00,17.00,35.00,0.00,18.24,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,90.05,152.68,4.79,7.58,84.42,141.89,91.97,248.08,73.68,73.68,2287.26,14708.61,594338.34,102.85,16.27
3,16.00,68.00,0.00,0.00,16.00,68.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,225.50,441.71,4.00,6.00,219.58,441.71,64.24,558.95,207.03,193.03,5864.24,37936.53,1667451.55,337.50,117.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,30.00,107.75,0.00,0.00,30.00,107.75,0.00,55.96,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3866,463.93,923.46,1.00,2.00,395.07,716.89,742.04,1079.39,391.89,387.89,10313.93,56432.89,1278159.46,68.39,14.36
3867,297.93,1183.68,0.00,0.00,55.50,142.18,2562.75,218.64,14.00,14.00,308.00,1255.00,7813.00,0.00,0.00
3868,300.82,924.00,1.00,4.00,300.82,923.71,68.14,869.46,377.71,302.71,8994.04,54895.25,3633694.18,336.75,141.29
3869,221.07,792.96,0.00,0.00,11.00,39.00,1871.07,11.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [65]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.46697248, 0.66970803, 0.6558011 , 0.72303473, 0.56279926,
       0.57792075, 0.55419257])

In [66]:
scores.mean()

0.6014898476877153

# MRMR 10

In [67]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: invalid value encountered in true_divide
  correlation_coefficient /= X_norms

In [68]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [69]:
K = 10

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [70]:
selected

['AltCountLineBlank',
 'AltCountLineComment',
 'CountLineBlank',
 'CountLineInactive',
 'CountLineComment',
 'AltAvgLineComment',
 'CountLine',
 'SumEssential',
 'CountStmtExe',
 'AvgLineComment']

In [71]:
X_new = X[selected]
X_new

,AltCountLineBlank,AltCountLineComment,CountLineBlank,CountLineInactive,CountLineComment,AltAvgLineComment,CountLine,SumEssential,CountStmtExe,AvgLineComment
0,129.89,377.26,122.66,45.26,359.71,9.42,923.53,27.05,221.95,9.42
1,17.00,35.00,17.00,0.00,35.00,0.00,92.24,0.00,0.00,0.00
2,90.05,152.68,84.42,91.97,141.89,7.58,743.53,46.50,235.74,7.58
3,16.00,68.00,16.00,0.00,68.00,0.00,91.00,0.00,0.00,0.00
4,225.50,441.71,219.58,64.24,441.71,6.00,1684.68,96.05,625.66,6.00
...,...,...,...,...,...,...,...,...,...,...
3865,30.00,107.75,30.00,0.00,107.75,0.00,226.36,0.00,0.00,0.00
3866,463.93,923.46,395.07,742.04,716.89,2.00,3917.39,219.79,1077.43,2.00
3867,297.93,1183.68,55.50,2562.75,142.18,0.00,3051.07,14.00,7.00,0.00
3868,300.82,924.00,300.82,68.14,923.71,4.00,2996.64,210.14,1048.93,4.00
3869,221.07,792.96,11.00,1871.07,39.00,0.00,1993.07,0.00,0.00,0.00

In [72]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.59105505, 0.67189781, 0.72375691, 0.81368068, 0.61869245,
       0.47334559, 0.51520753])

In [74]:
scores.mean()

0.6296622872022581

# MRMR 15

In [75]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: invalid value encountered in true_divide
  correlation_coefficient /= X_norms

In [76]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [77]:
K = 15

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [78]:
selected

['AltCountLineBlank',
 'AltCountLineComment',
 'CountLineBlank',
 'CountLineInactive',
 'CountLineComment',
 'AltAvgLineComment',
 'CountLine',
 'SumEssential',
 'CountStmtExe',
 'AvgLineComment',
 'CountStmt',
 'AltCountLineCode',
 'CountSemicolon',
 'AltAvgLineBlank',
 'n2']

In [79]:
X_new = X[selected]
X_new

,AltCountLineBlank,AltCountLineComment,CountLineBlank,CountLineInactive,CountLineComment,AltAvgLineComment,CountLine,SumEssential,CountStmtExe,AvgLineComment,CountStmt,AltCountLineCode,CountSemicolon,AltAvgLineBlank,n2
0,129.89,377.26,122.66,45.26,359.71,9.42,923.53,27.05,221.95,9.42,327.26,445.95,238.89,6.00,418.18
1,17.00,35.00,17.00,0.00,35.00,0.00,92.24,0.00,0.00,0.00,18.24,59.24,18.24,0.00,0.00
2,90.05,152.68,84.42,91.97,141.89,7.58,743.53,46.50,235.74,7.58,317.32,529.74,248.08,4.79,423.58
3,16.00,68.00,16.00,0.00,68.00,0.00,91.00,0.00,0.00,0.00,0.00,44.00,0.00,0.00,0.00
4,225.50,441.71,219.58,64.24,441.71,6.00,1684.68,96.05,625.66,6.00,770.32,1038.03,558.95,4.00,1026.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,30.00,107.75,30.00,0.00,107.75,0.00,226.36,0.00,0.00,0.00,55.96,92.36,55.96,0.00,0.00
3866,463.93,923.46,395.07,742.04,716.89,2.00,3917.39,219.79,1077.43,2.00,1435.93,2586.50,1079.39,1.00,2381.86
3867,297.93,1183.68,55.50,2562.75,142.18,0.00,3051.07,14.00,7.00,0.00,239.64,1653.79,218.64,0.00,89.00
3868,300.82,924.00,300.82,68.14,923.71,4.00,2996.64,210.14,1048.93,4.00,1245.54,1889.57,869.46,1.00,1440.79
3869,221.07,792.96,11.00,1871.07,39.00,0.00,1993.07,0.00,0.00,0.00,11.00,1037.04,11.00,0.00,0.00

In [80]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.65149083, 0.66715328, 0.77845304, 0.73202316, 0.67348066,
       0.47334559, 0.56360276])

In [81]:
scores.mean()

0.6485070446719338

# MRMR HFS

In [82]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d + (d*(d-1)*(sum(red_FF)/len(red_FF))))**(1/2)
            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [83]:
FS = HSF(df, X)
FS

['AltAvgLineBlank', 'AltAvgLineCode', 'AltAvgLineComment', 'AltCountLineBlank', 'AltCountLineCode', 'AltCountLineComment', 'AvgCyclomatic', 'AvgCyclomaticModified', 'AvgCyclomaticStrict', 'AvgEssential', 'AvgLine', 'AvgLineBlank', 'AvgLineCode', 'AvgLineComment', 'CountClassBase', 'CountClassCoupled', 'CountClassDerived', 'CountDeclClass', 'CountDeclClassMethod', 'CountDeclClassVariable', 'CountDeclFunction', 'CountDeclInstanceMethod', 'CountDeclInstanceVariable', 'CountDeclInstanceVariablePrivate', 'CountDeclInstanceVariableProtected', 'CountDeclInstanceVariablePublic', 'CountDeclMethod', 'CountDeclMethodAll', 'CountDeclMethodConst', 'CountDeclMethodFriend', 'CountDeclMethodPrivate', 'CountDeclMethodProtected', 'CountDeclMethodPublic', 'CountInput', 'CountLine', 'CountLineBlank', 'CountLineCode', 'CountLineCodeDecl', 'CountLineCodeExe', 'CountLineComment', 'CountLineInactive', 'CountLinePreprocessor', 'CountOutput', 'CountPath', 'CountSemicolon', 'CountStmt', 'CountStmtDecl', 'CountStmtEmpty', 'CountStmtExe', 'Cyclomatic', 'CyclomaticModified', 'CyclomaticStrict', 'Essential', 'Knots', 'MaxCyclomatic', 'MaxCyclomaticModified', 'MaxCyclomaticStrict', 'MaxEssentialKnots', 'MaxInheritanceTree', 'MaxNesting', 'MinEssentialKnots', 'PercentLackOfCohesion', 'RatioCommentToCode', 'SumCyclomatic', 'SumCyclomaticModified', 'SumCyclomaticStrict', 'SumEssential', 'n1', 'n2', 'N1', 'N2', 'Len', 'Voc', 'Vol', 'Dif', 'Eff', 'AllocOps', 'DeallocOps', 'DerefUse', 'UniqueDerefUse', 'DerefSet', 'UniqueDerefSet']

C:\Users\acer\AppData\Local\Temp\ipykernel_9028\2073211282.py:81: RuntimeWarning: invalid value encountered in double_scalars
  fscore = inter_class / intra_class
C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\scipy\stats\_stats_py.py:4068: PearsonRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(PearsonRConstantInputWarning())
C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\scipy\spatial\distance.py:630: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)

['AltCountLineBlank']

In [84]:
X_new = X[FS]

In [85]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.53176606, 0.57062044, 0.66243094, 0.63345521, 0.61418048,
       0.52685866, 0.61082171])

In [86]:
scores.mean()

0.5928762131507436

# HFS NEW

In [87]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d - (sum(red_FF)/len(red_FF)))**(1/2)

            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [88]:
FS = HSF(df, X)
FS

['AltAvgLineBlank', 'AltAvgLineCode', 'AltAvgLineComment', 'AltCountLineBlank', 'AltCountLineCode', 'AltCountLineComment', 'AvgCyclomatic', 'AvgCyclomaticModified', 'AvgCyclomaticStrict', 'AvgEssential', 'AvgLine', 'AvgLineBlank', 'AvgLineCode', 'AvgLineComment', 'CountClassBase', 'CountClassCoupled', 'CountClassDerived', 'CountDeclClass', 'CountDeclClassMethod', 'CountDeclClassVariable', 'CountDeclFunction', 'CountDeclInstanceMethod', 'CountDeclInstanceVariable', 'CountDeclInstanceVariablePrivate', 'CountDeclInstanceVariableProtected', 'CountDeclInstanceVariablePublic', 'CountDeclMethod', 'CountDeclMethodAll', 'CountDeclMethodConst', 'CountDeclMethodFriend', 'CountDeclMethodPrivate', 'CountDeclMethodProtected', 'CountDeclMethodPublic', 'CountInput', 'CountLine', 'CountLineBlank', 'CountLineCode', 'CountLineCodeDecl', 'CountLineCodeExe', 'CountLineComment', 'CountLineInactive', 'CountLinePreprocessor', 'CountOutput', 'CountPath', 'CountSemicolon', 'CountStmt', 'CountStmtDecl', 'CountStmtEmpty', 'CountStmtExe', 'Cyclomatic', 'CyclomaticModified', 'CyclomaticStrict', 'Essential', 'Knots', 'MaxCyclomatic', 'MaxCyclomaticModified', 'MaxCyclomaticStrict', 'MaxEssentialKnots', 'MaxInheritanceTree', 'MaxNesting', 'MinEssentialKnots', 'PercentLackOfCohesion', 'RatioCommentToCode', 'SumCyclomatic', 'SumCyclomaticModified', 'SumCyclomaticStrict', 'SumEssential', 'n1', 'n2', 'N1', 'N2', 'Len', 'Voc', 'Vol', 'Dif', 'Eff', 'AllocOps', 'DeallocOps', 'DerefUse', 'UniqueDerefUse', 'DerefSet', 'UniqueDerefSet']

C:\Users\acer\AppData\Local\Temp\ipykernel_9028\4067302685.py:82: RuntimeWarning: invalid value encountered in double_scalars
  fscore = inter_class / intra_class
C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\scipy\stats\_stats_py.py:4068: PearsonRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(PearsonRConstantInputWarning())
C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\scipy\spatial\distance.py:630: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)

['AltCountLineBlank']

In [89]:
X_new = X[FS]

In [90]:
cv = KFold(n_splits=7, random_state=37, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, X_new, Y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([0.53176606, 0.57062044, 0.66243094, 0.63345521, 0.61418048,
       0.52685866, 0.61082171])

In [91]:
scores.mean()

0.5928762131507436