In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('ant-1.csv')
df

,id,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,defects
0,1,3,1,0,10,18,3,1,9,1,...,0.000000,0,0.000000,0.444444,0,0,32.666667,1,0.6667,0
1,2,5,2,0,4,13,0,1,4,4,...,1.000000,1,0.700000,0.500000,0,0,13.400000,1,0.6000,0
2,3,1,2,0,1,3,0,0,1,1,...,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.0000,0
3,4,8,1,9,13,20,12,9,4,8,...,0.200000,1,0.000000,0.406250,0,0,11.000000,1,0.8750,0
4,5,9,3,0,5,26,16,0,5,7,...,1.000000,0,0.800000,0.388889,0,0,19.000000,2,1.0000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,741,92,3,0,34,261,3726,8,34,81,...,0.970588,11,0.291339,0.112476,2,2,28.021739,15,1.5543,4
741,742,6,3,6,10,10,3,7,3,6,...,1.000000,0,0.857143,0.500000,0,0,6.500000,3,1.5000,0
742,743,7,3,5,9,26,0,5,4,6,...,1.000000,0,0.857143,0.314286,1,3,19.000000,3,1.5714,0
743,744,5,2,0,8,34,8,1,7,3,...,1.000000,0,0.884615,1.000000,0,0,42.000000,11,3.4000,1
744,745,2,1,0,2,18,0,0,2,2,...,1.000000,0,0.000000,0.750000,0,0,40.000000,6,3.0000,0

In [11]:
df.drop(['id'], axis=1, inplace=True)

In [12]:
df['defects'].unique()

array([ 0,  1,  3,  2,  6,  4,  8,  5, 10,  7], dtype=int64)

In [13]:
df['defects'].replace([1,  3,  2,  6,  4,  8,  5, 10,  7], 1, inplace=True)
df['defects'].unique()

array([0, 1], dtype=int64)

In [14]:
df = df.rename({'defects':'class'}, axis=1)
df

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,3,1,0,10,18,3,1,9,1,1.100000,...,0.000000,0,0.000000,0.444444,0,0,32.666667,1,0.6667,0
1,5,2,0,4,13,0,1,4,4,0.625000,...,1.000000,1,0.700000,0.500000,0,0,13.400000,1,0.6000,0
2,1,2,0,1,3,0,0,1,1,2.000000,...,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.0000,0
3,8,1,9,13,20,12,9,4,8,0.800000,...,0.200000,1,0.000000,0.406250,0,0,11.000000,1,0.8750,0
4,9,3,0,5,26,16,0,5,7,0.750000,...,1.000000,0,0.800000,0.388889,0,0,19.000000,2,1.0000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,92,3,0,34,261,3726,8,34,81,0.960246,...,0.970588,11,0.291339,0.112476,2,2,28.021739,15,1.5543,1
741,6,3,6,10,10,3,7,3,6,0.400000,...,1.000000,0,0.857143,0.500000,0,0,6.500000,3,1.5000,0
742,7,3,5,9,26,0,5,4,6,0.000000,...,1.000000,0,0.857143,0.314286,1,3,19.000000,3,1.5714,0
743,5,2,0,8,34,8,1,7,3,0.500000,...,1.000000,0,0.884615,1.000000,0,0,42.000000,11,3.4000,1
744,2,1,0,2,18,0,0,2,2,0.000000,...,1.000000,0,0.000000,0.750000,0,0,40.000000,6,3.0000,0

In [15]:
df[df['class'] == 0]

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,3,1,0,10,18,3,1,9,1,1.100,...,0.0,0,0.000000,0.444444,0,0,32.666667,1,0.6667,0
1,5,2,0,4,13,0,1,4,4,0.625,...,1.0,1,0.700000,0.500000,0,0,13.400000,1,0.6000,0
2,1,2,0,1,3,0,0,1,1,2.000,...,0.0,0,1.000000,1.000000,0,0,6.000000,0,0.0000,0
3,8,1,9,13,20,12,9,4,8,0.800,...,0.2,1,0.000000,0.406250,0,0,11.000000,1,0.8750,0
5,3,2,5,7,4,1,6,1,2,0.500,...,1.0,0,0.750000,0.555556,0,0,4.000000,1,0.6667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,6,2,0,5,23,9,1,5,3,1.050,...,1.0,0,0.864865,0.555556,2,3,25.000000,4,1.8333,0
739,3,4,0,4,11,0,0,4,3,0.000,...,1.0,0,0.962264,0.666667,1,1,16.333333,1,0.6667,0
741,6,3,6,10,10,3,7,3,6,0.400,...,1.0,0,0.857143,0.500000,0,0,6.500000,3,1.5000,0
742,7,3,5,9,26,0,5,4,6,0.000,...,1.0,0,0.857143,0.314286,1,3,19.000000,3,1.5714,0
744,2,1,0,2,18,0,0,2,2,0.000,...,1.0,0,0.000000,0.750000,0,0,40.000000,6,3.0000,0

In [16]:
X = df.drop(['class'], axis=1)
X

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc
0,3,1,0,10,18,3,1,9,1,1.100000,106,0.000000,0,0.000000,0.444444,0,0,32.666667,1,0.6667
1,5,2,0,4,13,0,1,4,4,0.625000,76,1.000000,1,0.700000,0.500000,0,0,13.400000,1,0.6000
2,1,2,0,1,3,0,0,1,1,2.000000,7,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.0000
3,8,1,9,13,20,12,9,4,8,0.800000,101,0.200000,1,0.000000,0.406250,0,0,11.000000,1,0.8750
4,9,3,0,5,26,16,0,5,7,0.750000,185,1.000000,0,0.800000,0.388889,0,0,19.000000,2,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,92,3,0,34,261,3726,8,34,81,0.960246,2704,0.970588,11,0.291339,0.112476,2,2,28.021739,15,1.5543
741,6,3,6,10,10,3,7,3,6,0.400000,46,1.000000,0,0.857143,0.500000,0,0,6.500000,3,1.5000
742,7,3,5,9,26,0,5,4,6,0.000000,141,1.000000,0,0.857143,0.314286,1,3,19.000000,3,1.5714
743,5,2,0,8,34,8,1,7,3,0.500000,216,1.000000,0,0.884615,1.000000,0,0,42.000000,11,3.4000
744,2,1,0,2,18,0,0,2,2,0.000000,83,1.000000,0,0.000000,0.750000,0,0,40.000000,6,3.0000

In [17]:
Y = df['class']
Y

0      0
1      0
2      0
3      0
4      1
      ..
740    1
741    0
742    0
743    1
744    0
Name: class, Length: 745, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

# All Features

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

### Support Vector Machine

In [20]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### Support Vector Machine

In [21]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### KNeighborsClassifier

In [22]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7767857142857143
Precision :  0.5945945945945946
Recall :  0.38596491228070173
F1 Score :  0.4680851063829787
AUC :  0.6480722764996322

### Gaussian Naive Bayes

In [23]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7857142857142857
Precision :  0.5882352941176471
Recall :  0.5263157894736842
F1 Score :  0.5555555555555555
AUC :  0.700283643239836

# PEARSON CORRELATION

In [24]:
cor = df.corr()
cor_target = abs(cor['class'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.35]
relevant_features

wmc       0.433436
rfc       0.510690
ce        0.410585
npm       0.382014
loc       0.473067
max_cc    0.408716
class     1.000000
Name: class, dtype: float64

In [25]:
X_new = df[['wmc', 'rfc', 'ce', 'npm', 'loc', 'max_cc']]
X_new

     wmc  rfc  ce  npm   loc  max_cc
0      3   18   9    1   106       1
1      5   13   4    4    76       1
2      1    3   1    1     7       0
3      8   20   4    8   101       1
4      9   26   5    7   185       2
..   ...  ...  ..  ...   ...     ...
740   92  261  34   81  2704      15
741    6   10   3    6    46       3
742    7   26   4    6   141       3
743    5   34   7    3   216      11
744    2   18   2    2    83       6

[745 rows x 6 columns]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [27]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7991071428571429
Precision :  0.6304347826086957
Recall :  0.5087719298245614
F1 Score :  0.5631067961165049
AUC :  0.7034877613194663

### Support Vector Machine

In [28]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8035714285714286
Precision :  0.7096774193548387
Recall :  0.38596491228070173
F1 Score :  0.4999999999999999
AUC :  0.6660363483559197

### KNeighborsClassifier

In [29]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7946428571428571
Precision :  0.627906976744186
Recall :  0.47368421052631576
F1 Score :  0.5399999999999999
AUC :  0.6889379136463915

### Gaussian Naive Bayes

In [30]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8035714285714286
Precision :  0.6511627906976745
Recall :  0.49122807017543857
F1 Score :  0.5599999999999999
AUC :  0.7007038554470006

# INFORMATION GAIN 10

In [31]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.09527865, 0.        , 0.00719943, 0.06570106, 0.13665908,
       0.09599407, 0.        , 0.06625855, 0.07909153, 0.09522418,
       0.14326757, 0.04400224, 0.05388827, 0.0166266 , 0.08503467,
       0.03494354, 0.        , 0.08315463, 0.07110563, 0.04384367])

In [32]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [33]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.095279
1      dit  0.000000
2      noc  0.007199
3      cbo  0.065701
4      rfc  0.136659
5     lcom  0.095994
6       ca  0.000000
7       ce  0.066259
8      npm  0.079092
9    lcom3  0.095224
10     loc  0.143268
11     dam  0.044002
12     moa  0.053888
13     mfa  0.016627
14     cam  0.085035
15      ic  0.034944
16     cbm  0.000000
17     amc  0.083155
18  max_cc  0.071106
19  avg_cc  0.043844

In [34]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
10     loc  0.143268
4      rfc  0.136659
5     lcom  0.095994
0      wmc  0.095279
9    lcom3  0.095224
14     cam  0.085035
17     amc  0.083155
8      npm  0.079092
18  max_cc  0.071106
7       ce  0.066259

In [35]:
FS = list(temp_sort['col'][:10])
FS

['loc', 'rfc', 'lcom', 'wmc', 'lcom3', 'cam', 'amc', 'npm', 'max_cc', 'ce']

In [36]:
X_new = df[FS]
X_new

      loc  rfc  lcom  wmc     lcom3       cam        amc  npm  max_cc  ce
0     106   18     3    3  1.100000  0.444444  32.666667    1       1   9
1      76   13     0    5  0.625000  0.500000  13.400000    4       1   4
2       7    3     0    1  2.000000  1.000000   6.000000    1       0   1
3     101   20    12    8  0.800000  0.406250  11.000000    8       1   4
4     185   26    16    9  0.750000  0.388889  19.000000    7       2   5
..    ...  ...   ...  ...       ...       ...        ...  ...     ...  ..
740  2704  261  3726   92  0.960246  0.112476  28.021739   81      15  34
741    46   10     3    6  0.400000  0.500000   6.500000    6       3   3
742   141   26     0    7  0.000000  0.314286  19.000000    6       3   4
743   216   34     8    5  0.500000  1.000000  42.000000    3      11   7
744    83   18     0    2  0.000000  0.750000  40.000000    2       6   2

[745 rows x 10 columns]

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [38]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8258928571428571
Precision :  0.7368421052631579
Recall :  0.49122807017543857
F1 Score :  0.5894736842105264
AUC :  0.7156739153272402

### Support Vector Machine

In [39]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### KNeighborsClassifier

In [40]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7857142857142857
Precision :  0.6285714285714286
Recall :  0.38596491228070173
F1 Score :  0.4782608695652174
AUC :  0.654060300451728

### Gaussian Naive Bayes

In [41]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.6744186046511628
Recall :  0.5087719298245614
F1 Score :  0.58
AUC :  0.7124697972476101

# INFORMATION GAIN 15

In [42]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.08708463, 0.01080654, 0.00450579, 0.05255613, 0.12576247,
       0.10077042, 0.0019578 , 0.12539432, 0.04602032, 0.09147242,
       0.13626037, 0.05233674, 0.04536946, 0.        , 0.07503872,
       0.        , 0.02542953, 0.0839722 , 0.07931148, 0.04605107])

In [43]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [44]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.087085
1      dit  0.010807
2      noc  0.004506
3      cbo  0.052556
4      rfc  0.125762
5     lcom  0.100770
6       ca  0.001958
7       ce  0.125394
8      npm  0.046020
9    lcom3  0.091472
10     loc  0.136260
11     dam  0.052337
12     moa  0.045369
13     mfa  0.000000
14     cam  0.075039
15      ic  0.000000
16     cbm  0.025430
17     amc  0.083972
18  max_cc  0.079311
19  avg_cc  0.046051

In [45]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:15]

       col     score
10     loc  0.136260
4      rfc  0.125762
7       ce  0.125394
5     lcom  0.100770
9    lcom3  0.091472
0      wmc  0.087085
17     amc  0.083972
18  max_cc  0.079311
14     cam  0.075039
3      cbo  0.052556
11     dam  0.052337
19  avg_cc  0.046051
8      npm  0.046020
12     moa  0.045369
16     cbm  0.025430

In [46]:
FS = list(temp_sort['col'][:15])
FS

['loc',
 'rfc',
 'ce',
 'lcom',
 'lcom3',
 'wmc',
 'amc',
 'max_cc',
 'cam',
 'cbo',
 'dam',
 'avg_cc',
 'npm',
 'moa',
 'cbm']

In [47]:
X_new = df[FS]
X_new

,loc,rfc,ce,lcom,lcom3,wmc,amc,max_cc,cam,cbo,dam,avg_cc,npm,moa,cbm
0,106,18,9,3,1.100000,3,32.666667,1,0.444444,10,0.000000,0.6667,1,0,0
1,76,13,4,0,0.625000,5,13.400000,1,0.500000,4,1.000000,0.6000,4,1,0
2,7,3,1,0,2.000000,1,6.000000,0,1.000000,1,0.000000,0.0000,1,0,0
3,101,20,4,12,0.800000,8,11.000000,1,0.406250,13,0.200000,0.8750,8,1,0
4,185,26,5,16,0.750000,9,19.000000,2,0.388889,5,1.000000,1.0000,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,2704,261,34,3726,0.960246,92,28.021739,15,0.112476,34,0.970588,1.5543,81,11,2
741,46,10,3,3,0.400000,6,6.500000,3,0.500000,10,1.000000,1.5000,6,0,0
742,141,26,4,0,0.000000,7,19.000000,3,0.314286,9,1.000000,1.5714,6,0,3
743,216,34,7,8,0.500000,5,42.000000,11,1.000000,8,1.000000,3.4000,3,0,0
744,83,18,2,0,0.000000,2,40.000000,6,0.750000,2,1.000000,3.0000,2,0,0

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [49]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8303571428571429
Precision :  0.7567567567567568
Recall :  0.49122807017543857
F1 Score :  0.5957446808510638
AUC :  0.7186679273032882

### Support Vector Machine

In [50]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### KNeighborsClassifier

In [51]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.78125
Precision :  0.6111111111111112
Recall :  0.38596491228070173
F1 Score :  0.4731182795698925
AUC :  0.6510662884756802

### Gaussian Naive Bayes

In [52]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7946428571428571
Precision :  0.6170212765957447
Recall :  0.5087719298245614
F1 Score :  0.5576923076923077
AUC :  0.7004937493434185

# FISHER SCORE

In [53]:
FScore = []

for m in  range(len(col_list)):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        FScore.append(inter_class / intra_class)

FScore

[0.23132561897827436,
 0.00142064396594741,
 0.0005680565663847185,
 0.016447867152652555,
 0.3528215105619669,
 0.07506239179016846,
 0.0023502457894348967,
 0.20276128074953587,
 0.17087046193416328,
 0.014605402761677294,
 0.28831497202861095,
 0.0408997162258003,
 0.0970473098829611,
 0.0002867157024330744,
 0.12112777473384707,
 0.018635478978286574,
 0.016141588975106366,
 0.0022362681268192656,
 0.2005504020254722,
 0.09161610093745451]

In [54]:
temp = pd.DataFrame(list(zip(col_list, FScore)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.231326
1      dit  0.001421
2      noc  0.000568
3      cbo  0.016448
4      rfc  0.352822
5     lcom  0.075062
6       ca  0.002350
7       ce  0.202761
8      npm  0.170870
9    lcom3  0.014605
10     loc  0.288315
11     dam  0.040900
12     moa  0.097047
13     mfa  0.000287
14     cam  0.121128
15      ic  0.018635
16     cbm  0.016142
17     amc  0.002236
18  max_cc  0.200550
19  avg_cc  0.091616

In [55]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
4      rfc  0.352822
10     loc  0.288315
0      wmc  0.231326
7       ce  0.202761
18  max_cc  0.200550
8      npm  0.170870
14     cam  0.121128
12     moa  0.097047
19  avg_cc  0.091616
5     lcom  0.075062

In [56]:
FS = list(temp_sort['col'][:10])
FS

['rfc', 'loc', 'wmc', 'ce', 'max_cc', 'npm', 'cam', 'moa', 'avg_cc', 'lcom']

In [57]:
X_new = df[FS]
X_new

     rfc   loc  wmc  ce  max_cc  npm       cam  moa  avg_cc  lcom
0     18   106    3   9       1    1  0.444444    0  0.6667     3
1     13    76    5   4       1    4  0.500000    1  0.6000     0
2      3     7    1   1       0    1  1.000000    0  0.0000     0
3     20   101    8   4       1    8  0.406250    1  0.8750    12
4     26   185    9   5       2    7  0.388889    0  1.0000    16
..   ...   ...  ...  ..     ...  ...       ...  ...     ...   ...
740  261  2704   92  34      15   81  0.112476   11  1.5543  3726
741   10    46    6   3       3    6  0.500000    0  1.5000     3
742   26   141    7   4       3    6  0.314286    0  1.5714     0
743   34   216    5   7      11    3  1.000000    0  3.4000     8
744   18    83    2   2       6    2  0.750000    0  3.0000     0

[745 rows x 10 columns]

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [59]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.6923076923076923
Recall :  0.47368421052631576
F1 Score :  0.5625
AUC :  0.700913961550583

### Support Vector Machine

In [60]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.7333333333333333
Recall :  0.38596491228070173
F1 Score :  0.5057471264367815
AUC :  0.6690303603319676

### KNeighborsClassifier

In [61]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7857142857142857
Precision :  0.6153846153846154
Recall :  0.42105263157894735
F1 Score :  0.5
AUC :  0.6656161361487551

### Gaussian Naive Bayes

In [62]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7991071428571429
Precision :  0.6428571428571429
Recall :  0.47368421052631576
F1 Score :  0.5454545454545454
AUC :  0.6919319256224393

# SVM RFE 10

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [64]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=10)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [65]:
X_train = X_train.loc[:, rfe.support_]
X_train

     wmc  rfc  lcom  ce     lcom3  loc       cam        amc  max_cc  avg_cc
633    7   11     7   0  0.333333  105  0.714286  13.571429       7  1.4286
124   14   49     7   6  0.735043  488  0.250000  33.214286      12  1.7857
604    8   19     8   5  1.000000  165  0.687500  18.375000       2  1.0000
586    3    5     3   0  2.000000   24  0.666667   7.000000       4  1.6667
359    3    5     0   0  0.000000   45  0.666667  13.333333       2  1.0000
..   ...  ...   ...  ..       ...  ...       ...        ...     ...     ...
31    14   29    85   8  0.576923  108  0.321429   6.571429       4  1.2857
488    5   44     8   8  0.625000  298  0.542857  57.800000       1  0.6000
40    11   23    39   0  0.483333  136  0.348485  10.818182       1  0.5455
742    7   26     0   4  0.000000  141  0.314286  19.000000       3  1.5714
595   31  107   391  19  0.922807  977  0.150000  29.903226       3  1.1290

[521 rows x 10 columns]

In [66]:
X_test = X_test.loc[:, rfe.support_]
X_test

     wmc  rfc  lcom  ce     lcom3   loc       cam        amc  max_cc  avg_cc
66     7   26     0   2  0.500000   218  0.476190  29.571429       5  2.2857
248    4    7     0   4  0.000000    34  0.500000   7.250000       2  1.0000
616    4   14     0   4  0.500000   108  0.750000  25.500000       1  0.7500
373    7   24    19   1  0.666667   373  0.416667  52.142857       6  2.0000
96    19   21   145   5  0.954861   143  0.230263   5.684211       1  0.9474
..   ...  ...   ...  ..       ...   ...       ...        ...     ...     ...
567    1    2     0   1  2.000000     4  1.000000   3.000000       0  0.0000
474   34  106   435   9  0.933014  1020  0.188552  28.441176      46  3.0588
202   13   37    56  10  0.770833   269  0.205128  19.384615       7  1.3846
550   27   41   321  23  0.000000   191  0.084656   6.037037       4  1.1852
476   23  126   161  17  0.770833  2117  0.148760  90.000000      53  4.5217

[224 rows x 10 columns]

### RandomForest

In [67]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.7142857142857143
Recall :  0.43859649122807015
F1 Score :  0.5434782608695652
AUC :  0.689358125853556

### Support Vector Machine

In [68]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### KNeighborsClassifier

In [69]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.78125
Precision :  0.6111111111111112
Recall :  0.38596491228070173
F1 Score :  0.4731182795698925
AUC :  0.6510662884756802

### Gaussian Naive Bayes

In [70]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8169642857142857
Precision :  0.6904761904761905
Recall :  0.5087719298245614
F1 Score :  0.5858585858585859
AUC :  0.7154638092236579

# SVM RFE 15

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [72]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=15)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [73]:
X_train = X_train.loc[:, rfe.support_]
X_train

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,mfa,cam,amc,max_cc,avg_cc
633,7,1,11,7,1,0,7,0.333333,105,1.000000,0.000000,0.714286,13.571429,7,1.4286
124,14,7,49,7,1,6,7,0.735043,488,1.000000,0.700000,0.250000,33.214286,12,1.7857
604,8,5,19,8,0,5,7,1.000000,165,0.300000,0.562500,0.687500,18.375000,2,1.0000
586,3,1,5,3,1,0,3,2.000000,24,0.000000,0.000000,0.666667,7.000000,4,1.6667
359,3,1,5,0,1,0,3,0.000000,45,1.000000,0.000000,0.666667,13.333333,2,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,14,11,29,85,3,8,11,0.576923,108,1.000000,0.759259,0.321429,6.571429,4,1.2857
488,5,9,44,8,1,8,3,0.625000,298,1.000000,0.842105,0.542857,57.800000,1,0.6000
40,11,1,23,39,1,0,10,0.483333,136,1.000000,0.454545,0.348485,10.818182,1,0.5455
742,7,9,26,0,5,4,6,0.000000,141,1.000000,0.857143,0.314286,19.000000,3,1.5714
595,31,19,107,391,0,19,28,0.922807,977,0.894737,0.560606,0.150000,29.903226,3,1.1290

In [74]:
X_test = X_test.loc[:, rfe.support_]
X_test

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,mfa,cam,amc,max_cc,avg_cc
66,7,3,26,0,1,2,7,0.500000,218,1.000000,0.000000,0.476190,29.571429,5,2.2857
248,4,4,7,0,0,4,3,0.000000,34,1.000000,0.918919,0.500000,7.250000,2,1.0000
616,4,4,14,0,0,4,4,0.500000,108,0.500000,0.944444,0.750000,25.500000,1,0.7500
373,7,2,24,19,1,1,3,0.666667,373,0.000000,0.000000,0.416667,52.142857,6,2.0000
96,19,9,21,145,4,5,18,0.954861,143,1.000000,0.000000,0.230263,5.684211,1,0.9474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,1,3,2,0,2,1,1,2.000000,4,0.000000,1.000000,1.000000,3.000000,0,0.0000
474,34,9,106,435,0,9,15,0.933014,1020,0.947368,0.536232,0.188552,28.441176,46,3.0588
202,13,12,37,56,4,10,4,0.770833,269,1.000000,0.000000,0.205128,19.384615,7,1.3846
550,27,25,41,321,2,23,27,0.000000,191,1.000000,0.535714,0.084656,6.037037,4,1.1852
476,23,17,126,161,2,17,5,0.770833,2117,0.791667,0.000000,0.148760,90.000000,53,4.5217

### RandomForest

In [75]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8258928571428571
Precision :  0.75
Recall :  0.47368421052631576
F1 Score :  0.5806451612903226
AUC :  0.7098959974787268

### Support Vector Machine

In [76]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.71875
Recall :  0.40350877192982454
F1 Score :  0.5168539325842696
AUC :  0.6748082781804812

### KNeighborsClassifier

In [77]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7767857142857143
Precision :  0.5945945945945946
Recall :  0.38596491228070173
F1 Score :  0.4680851063829787
AUC :  0.6480722764996322

### Gaussian Naive Bayes

In [78]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.78125
Precision :  0.5869565217391305
Recall :  0.47368421052631576
F1 Score :  0.5242718446601942
AUC :  0.6799558777182477

# MRMR 10

In [79]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [80]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [81]:
K = 10

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [82]:
selected

['rfc', 'max_cc', 'loc', 'ce', 'wmc', 'npm', 'avg_cc', 'cam', 'moa', 'lcom']

In [83]:
X_new = X[selected]
X_new

     rfc  max_cc   loc  ce  wmc  npm  avg_cc       cam  moa  lcom
0     18       1   106   9    3    1  0.6667  0.444444    0     3
1     13       1    76   4    5    4  0.6000  0.500000    1     0
2      3       0     7   1    1    1  0.0000  1.000000    0     0
3     20       1   101   4    8    8  0.8750  0.406250    1    12
4     26       2   185   5    9    7  1.0000  0.388889    0    16
..   ...     ...   ...  ..  ...  ...     ...       ...  ...   ...
740  261      15  2704  34   92   81  1.5543  0.112476   11  3726
741   10       3    46   3    6    6  1.5000  0.500000    0     3
742   26       3   141   4    7    6  1.5714  0.314286    0     0
743   34      11   216   7    5    3  3.4000  1.000000    0     8
744   18       6    83   2    2    2  3.0000  0.750000    0     0

[745 rows x 10 columns]

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [85]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8258928571428571
Precision :  0.725
Recall :  0.5087719298245614
F1 Score :  0.5979381443298969
AUC :  0.7214518331757538

### Support Vector Machine

In [86]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8080357142857143
Precision :  0.7333333333333333
Recall :  0.38596491228070173
F1 Score :  0.5057471264367815
AUC :  0.6690303603319676

### KNeighborsClassifier

In [87]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7857142857142857
Precision :  0.6153846153846154
Recall :  0.42105263157894735
F1 Score :  0.5
AUC :  0.6656161361487551

### Gaussian Naive Bayes

In [88]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7991071428571429
Precision :  0.6428571428571429
Recall :  0.47368421052631576
F1 Score :  0.5454545454545454
AUC :  0.6919319256224393

# MRMR 15

In [89]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [90]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [91]:
K = 15

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [92]:
selected

['rfc',
 'max_cc',
 'loc',
 'ce',
 'wmc',
 'npm',
 'avg_cc',
 'cam',
 'moa',
 'lcom',
 'dam',
 'ic',
 'cbm',
 'cbo',
 'lcom3']

In [93]:
X_new = X[selected]
X_new

,rfc,max_cc,loc,ce,wmc,npm,avg_cc,cam,moa,lcom,dam,ic,cbm,cbo,lcom3
0,18,1,106,9,3,1,0.6667,0.444444,0,3,0.000000,0,0,10,1.100000
1,13,1,76,4,5,4,0.6000,0.500000,1,0,1.000000,0,0,4,0.625000
2,3,0,7,1,1,1,0.0000,1.000000,0,0,0.000000,0,0,1,2.000000
3,20,1,101,4,8,8,0.8750,0.406250,1,12,0.200000,0,0,13,0.800000
4,26,2,185,5,9,7,1.0000,0.388889,0,16,1.000000,0,0,5,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,261,15,2704,34,92,81,1.5543,0.112476,11,3726,0.970588,2,2,34,0.960246
741,10,3,46,3,6,6,1.5000,0.500000,0,3,1.000000,0,0,10,0.400000
742,26,3,141,4,7,6,1.5714,0.314286,0,0,1.000000,1,3,9,0.000000
743,34,11,216,7,5,3,3.4000,1.000000,0,8,1.000000,0,0,8,0.500000
744,18,6,83,2,2,2,3.0000,0.750000,0,0,1.000000,0,0,2,0.000000

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [95]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.7142857142857143
Recall :  0.43859649122807015
F1 Score :  0.5434782608695652
AUC :  0.689358125853556

### KNeighborsClassifier

In [96]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.78125
Precision :  0.6
Recall :  0.42105263157894735
F1 Score :  0.4948453608247421
AUC :  0.6626221241727072

### Support Vector Machine

In [97]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.7419354838709677
Recall :  0.40350877192982454
F1 Score :  0.5227272727272727
AUC :  0.6778022901565289

### KNeighborsClassifier

In [98]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.78125
Precision :  0.6
Recall :  0.42105263157894735
F1 Score :  0.4948453608247421
AUC :  0.6626221241727072

### Gaussian Naive Bayes

In [99]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7946428571428571
Precision :  0.6170212765957447
Recall :  0.5087719298245614
F1 Score :  0.5576923076923077
AUC :  0.7004937493434185

# MRMR HFS

In [100]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d + (d*(d-1)*(sum(red_FF)/len(red_FF))))**(1/2)
            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [101]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['rfc', 'noc']

In [102]:
X_new = X[FS]

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [104]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7946428571428571
Precision :  0.6666666666666666
Recall :  0.38596491228070173
F1 Score :  0.4888888888888889
AUC :  0.6600483244038239

### Support Vector Machine

In [105]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8214285714285714
Precision :  0.7741935483870968
Recall :  0.42105263157894735
F1 Score :  0.5454545454545454
AUC :  0.6895682319571383

### KNeighborsClassifier

In [106]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8035714285714286
Precision :  0.6666666666666666
Recall :  0.45614035087719296
F1 Score :  0.5416666666666666
AUC :  0.6891480197499738

### Gaussian Naive Bayes

In [107]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8303571428571429
Precision :  0.7111111111111111
Recall :  0.5614035087719298
F1 Score :  0.6274509803921567
AUC :  0.7417795986973421

# HFS NEW

In [108]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d - (sum(red_FF)/len(red_FF)))**(1/2)

            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [109]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['rfc', 'wmc']

In [110]:
X_new = X[FS]

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [112]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7767857142857143
Precision :  0.5853658536585366
Recall :  0.42105263157894735
F1 Score :  0.48979591836734687
AUC :  0.6596281121966593

### Support Vector Machine

In [113]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8169642857142857
Precision :  0.7666666666666667
Recall :  0.40350877192982454
F1 Score :  0.528735632183908
AUC :  0.6807963021325769

### KNeighborsClassifier

In [114]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8169642857142857
Precision :  0.7222222222222222
Recall :  0.45614035087719296
F1 Score :  0.5591397849462365
AUC :  0.6981300556781175

### Gaussian Naive Bayes

In [115]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8125
Precision :  0.7142857142857143
Recall :  0.43859649122807015
F1 Score :  0.5434782608695652
AUC :  0.689358125853556