In [94]:
import pandas as pd

In [95]:
df = pd.read_csv('ivy-2.csv')
df

,id,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,defects
0,1,28,1,0,32,82,374,26,7,24,...,0.166667,0,0.000000,0.226337,0,0,31.642857,23,2.6786,2
1,2,6,1,2,3,7,3,2,1,4,...,1.000000,0,0.000000,0.444444,0,0,4.666667,1,0.6667,0
2,3,4,2,0,5,6,4,1,4,2,...,1.000000,1,0.500000,0.500000,0,0,4.000000,1,0.5000,0
3,4,4,1,0,9,4,6,9,0,4,...,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
4,5,1,1,0,8,1,0,6,2,1,...,0.000000,0,0.000000,1.000000,0,0,0.000000,1,1.0000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,348,3,1,0,15,3,3,14,1,3,...,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
348,349,8,1,0,18,17,20,17,1,8,...,1.000000,1,0.000000,0.343750,1,1,16.125000,6,1.6250,0
349,350,10,1,0,15,10,45,12,3,10,...,0.000000,0,0.000000,0.366667,0,0,0.000000,1,1.0000,0
350,351,45,4,0,13,113,814,1,0,45,...,1.000000,0,0.603604,0.306667,3,5,12.666667,2,1.0000,0
351,352,7,1,0,10,44,19,4,7,4,...,0.500000,0,0.000000,0.354167,0,0,48.428571,1,0.7143,1

In [96]:
df.drop(['id'], axis=1, inplace=True)

In [97]:
df['defects'].unique()

array([2, 0, 1, 3], dtype=int64)

In [98]:
df['defects'].replace([1,  3,  2], 1, inplace=True)
df['defects'].unique()

array([1, 0], dtype=int64)

In [99]:
df = df.rename({'defects':'class'}, axis=1)
df

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,28,1,0,32,82,374,26,7,24,1.012346,...,0.166667,0,0.000000,0.226337,0,0,31.642857,23,2.6786,1
1,6,1,2,3,7,3,2,1,4,0.600000,...,1.000000,0,0.000000,0.444444,0,0,4.666667,1,0.6667,0
2,4,2,0,5,6,4,1,4,2,0.666667,...,1.000000,1,0.500000,0.500000,0,0,4.000000,1,0.5000,0
3,4,1,0,9,4,6,9,0,4,2.000000,...,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
4,1,1,0,8,1,0,6,2,1,2.000000,...,0.000000,0,0.000000,1.000000,0,0,0.000000,1,1.0000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,3,1,0,15,3,3,14,1,3,2.000000,...,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
348,8,1,0,18,17,20,17,1,8,0.464286,...,1.000000,1,0.000000,0.343750,1,1,16.125000,6,1.6250,0
349,10,1,0,15,10,45,12,3,10,2.000000,...,0.000000,0,0.000000,0.366667,0,0,0.000000,1,1.0000,0
350,45,4,0,13,113,814,1,0,45,0.943723,...,1.000000,0,0.603604,0.306667,3,5,12.666667,2,1.0000,0
351,7,1,0,10,44,19,4,7,4,0.916667,...,0.500000,0,0.000000,0.354167,0,0,48.428571,1,0.7143,1

In [100]:
df[df['class'] == 0]

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
1,6,1,2,3,7,3,2,1,4,0.600000,...,1.0,0,0.000000,0.444444,0,0,4.666667,1,0.6667,0
2,4,2,0,5,6,4,1,4,2,0.666667,...,1.0,1,0.500000,0.500000,0,0,4.000000,1,0.5000,0
3,4,1,0,9,4,6,9,0,4,2.000000,...,0.0,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
4,1,1,0,8,1,0,6,2,1,2.000000,...,0.0,0,0.000000,1.000000,0,0,0.000000,1,1.0000,0
6,5,1,0,8,26,0,1,7,4,0.625000,...,1.0,2,0.000000,0.314286,0,0,23.600000,4,1.6000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,7,1,5,9,8,13,5,4,7,0.750000,...,1.0,1,0.000000,0.314286,0,0,3.000000,1,0.8571,0
347,3,1,0,15,3,3,14,1,3,2.000000,...,0.0,0,0.000000,0.666667,0,0,0.000000,1,1.0000,0
348,8,1,0,18,17,20,17,1,8,0.464286,...,1.0,1,0.000000,0.343750,1,1,16.125000,6,1.6250,0
349,10,1,0,15,10,45,12,3,10,2.000000,...,0.0,0,0.000000,0.366667,0,0,0.000000,1,1.0000,0
350,45,4,0,13,113,814,1,0,45,0.943723,...,1.0,0,0.603604,0.306667,3,5,12.666667,2,1.0000,0

In [101]:
X = df.drop(['class'], axis=1)
X

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc
0,28,1,0,32,82,374,26,7,24,1.012346,926,0.166667,0,0.000000,0.226337,0,0,31.642857,23,2.6786
1,6,1,2,3,7,3,2,1,4,0.600000,36,1.000000,0,0.000000,0.444444,0,0,4.666667,1,0.6667
2,4,2,0,5,6,4,1,4,2,0.666667,21,1.000000,1,0.500000,0.500000,0,0,4.000000,1,0.5000
3,4,1,0,9,4,6,9,0,4,2.000000,4,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000
4,1,1,0,8,1,0,6,2,1,2.000000,1,0.000000,0,0.000000,1.000000,0,0,0.000000,1,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,3,1,0,15,3,3,14,1,3,2.000000,3,0.000000,0,0.000000,0.666667,0,0,0.000000,1,1.0000
348,8,1,0,18,17,20,17,1,8,0.464286,141,1.000000,1,0.000000,0.343750,1,1,16.125000,6,1.6250
349,10,1,0,15,10,45,12,3,10,2.000000,10,0.000000,0,0.000000,0.366667,0,0,0.000000,1,1.0000
350,45,4,0,13,113,814,1,0,45,0.943723,636,1.000000,0,0.603604,0.306667,3,5,12.666667,2,1.0000
351,7,1,0,10,44,19,4,7,4,0.916667,348,0.500000,0,0.000000,0.354167,0,0,48.428571,1,0.7143

In [102]:
Y = df['class']
Y

0      1
1      0
2      0
3      0
4      0
      ..
347    0
348    0
349    0
350    0
351    1
Name: class, Length: 352, dtype: int64

In [103]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

# All Features

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

### Support Vector Machine

In [105]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### Support Vector Machine

In [106]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [107]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.125
Recall :  0.1
F1 Score :  0.11111111111111112
AUC :  0.5135416666666668

### Gaussian Naive Bayes

In [108]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7452830188679245
Precision :  0.16
Recall :  0.4
F1 Score :  0.22857142857142856
AUC :  0.590625

# PEARSON CORRELATION

In [109]:
cor = df.corr()
cor_target = abs(cor['class'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.35]
relevant_features

rfc      0.439089
loc      0.439758
class    1.000000
Name: class, dtype: float64

In [110]:
X_new = df[['rfc', 'loc']]
X_new

     rfc  loc
0     82  926
1      7   36
2      6   21
3      4    4
4      1    1
..   ...  ...
347    3    3
348   17  141
349   10   10
350  113  636
351   44  348

[352 rows x 2 columns]

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [112]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### Support Vector Machine

In [113]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### KNeighborsClassifier

In [114]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [115]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7924528301886793
Precision :  0.2
Recall :  0.4
F1 Score :  0.26666666666666666
AUC :  0.6166666666666667

# INFORMATION GAIN 10

In [116]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.08532766, 0.0119685 , 0.        , 0.04910513, 0.09001665,
       0.04160665, 0.00946282, 0.07757651, 0.03286567, 0.06494056,
       0.0473778 , 0.        , 0.        , 0.03299913, 0.0674021 ,
       0.        , 0.        , 0.02442708, 0.04926062, 0.0355955 ])

In [117]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [118]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.085328
1      dit  0.011968
2      noc  0.000000
3      cbo  0.049105
4      rfc  0.090017
5     lcom  0.041607
6       ca  0.009463
7       ce  0.077577
8      npm  0.032866
9    lcom3  0.064941
10     loc  0.047378
11     dam  0.000000
12     moa  0.000000
13     mfa  0.032999
14     cam  0.067402
15      ic  0.000000
16     cbm  0.000000
17     amc  0.024427
18  max_cc  0.049261
19  avg_cc  0.035595

In [119]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
4      rfc  0.090017
0      wmc  0.085328
7       ce  0.077577
14     cam  0.067402
9    lcom3  0.064941
18  max_cc  0.049261
3      cbo  0.049105
10     loc  0.047378
5     lcom  0.041607
19  avg_cc  0.035595

In [120]:
FS = list(temp_sort['col'][:10])
FS

['rfc', 'wmc', 'ce', 'cam', 'lcom3', 'max_cc', 'cbo', 'loc', 'lcom', 'avg_cc']

In [121]:
X_new = df[FS]
X_new

     rfc  wmc  ce       cam     lcom3  max_cc  cbo  loc  lcom  avg_cc
0     82   28   7  0.226337  1.012346      23   32  926   374  2.6786
1      7    6   1  0.444444  0.600000       1    3   36     3  0.6667
2      6    4   4  0.500000  0.666667       1    5   21     4  0.5000
3      4    4   0  0.666667  2.000000       1    9    4     6  1.0000
4      1    1   2  1.000000  2.000000       1    8    1     0  1.0000
..   ...  ...  ..       ...       ...     ...  ...  ...   ...     ...
347    3    3   1  0.666667  2.000000       1   15    3     3  1.0000
348   17    8   1  0.343750  0.464286       6   18  141    20  1.6250
349   10   10   3  0.366667  2.000000       1   15   10    45  1.0000
350  113   45   0  0.306667  0.943723       2   13  636   814  1.0000
351   44    7   7  0.354167  0.916667       1   10  348    19  0.7143

[352 rows x 10 columns]

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [123]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.25
Recall :  0.3
F1 Score :  0.2727272727272727
AUC :  0.603125

### Support Vector Machine

In [124]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [125]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.1111111111111111
Recall :  0.1
F1 Score :  0.10526315789473685
AUC :  0.5083333333333333

### Gaussian Naive Bayes

In [126]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7452830188679245
Precision :  0.16
Recall :  0.4
F1 Score :  0.22857142857142856
AUC :  0.590625

# INFORMATION GAIN 15

In [127]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.07389603, 0.04904265, 0.        , 0.07216638, 0.0830298 ,
       0.0451238 , 0.        , 0.0616631 , 0.03546383, 0.07615446,
       0.04915975, 0.00580502, 0.01681591, 0.03012447, 0.06344798,
       0.        , 0.00644836, 0.02016571, 0.05145694, 0.02915057])

In [128]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [129]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.073896
1      dit  0.049043
2      noc  0.000000
3      cbo  0.072166
4      rfc  0.083030
5     lcom  0.045124
6       ca  0.000000
7       ce  0.061663
8      npm  0.035464
9    lcom3  0.076154
10     loc  0.049160
11     dam  0.005805
12     moa  0.016816
13     mfa  0.030124
14     cam  0.063448
15      ic  0.000000
16     cbm  0.006448
17     amc  0.020166
18  max_cc  0.051457
19  avg_cc  0.029151

In [130]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:15]

       col     score
4      rfc  0.083030
9    lcom3  0.076154
0      wmc  0.073896
3      cbo  0.072166
14     cam  0.063448
7       ce  0.061663
18  max_cc  0.051457
10     loc  0.049160
1      dit  0.049043
5     lcom  0.045124
8      npm  0.035464
13     mfa  0.030124
19  avg_cc  0.029151
17     amc  0.020166
12     moa  0.016816

In [131]:
FS = list(temp_sort['col'][:15])
FS

['rfc',
 'lcom3',
 'wmc',
 'cbo',
 'cam',
 'ce',
 'max_cc',
 'loc',
 'dit',
 'lcom',
 'npm',
 'mfa',
 'avg_cc',
 'amc',
 'moa']

In [132]:
X_new = df[FS]
X_new

,rfc,lcom3,wmc,cbo,cam,ce,max_cc,loc,dit,lcom,npm,mfa,avg_cc,amc,moa
0,82,1.012346,28,32,0.226337,7,23,926,1,374,24,0.000000,2.6786,31.642857,0
1,7,0.600000,6,3,0.444444,1,1,36,1,3,4,0.000000,0.6667,4.666667,0
2,6,0.666667,4,5,0.500000,4,1,21,2,4,2,0.500000,0.5000,4.000000,1
3,4,2.000000,4,9,0.666667,0,1,4,1,6,4,0.000000,1.0000,0.000000,0
4,1,2.000000,1,8,1.000000,2,1,1,1,0,1,0.000000,1.0000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,3,2.000000,3,15,0.666667,1,1,3,1,3,3,0.000000,1.0000,0.000000,0
348,17,0.464286,8,18,0.343750,1,6,141,1,20,8,0.000000,1.6250,16.125000,1
349,10,2.000000,10,15,0.366667,3,1,10,1,45,10,0.000000,1.0000,0.000000,0
350,113,0.943723,45,13,0.306667,0,2,636,4,814,45,0.603604,1.0000,12.666667,0
351,44,0.916667,7,10,0.354167,7,1,348,1,19,4,0.000000,0.7143,48.428571,0

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [134]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2
Recall :  0.2
F1 Score :  0.20000000000000004
AUC :  0.5583333333333332

### Support Vector Machine

In [135]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [136]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8301886792452831
Precision :  0.1
Recall :  0.1
F1 Score :  0.10000000000000002
AUC :  0.503125

### Gaussian Naive Bayes

In [137]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7547169811320755
Precision :  0.16666666666666666
Recall :  0.4
F1 Score :  0.23529411764705882
AUC :  0.5958333333333332

# FISHER SCORE

In [138]:
FScore = []

for m in  range(len(col_list)):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        FScore.append(inter_class / intra_class)

FScore

[0.132822067546136,
 0.0001507033627345551,
 0.0015432565363310666,
 0.08088203377858212,
 0.23884909904711737,
 0.023099062338739346,
 0.00826369076295656,
 0.12023404353921834,
 0.07293513542644917,
 0.005588244234717659,
 0.23975215487669665,
 0.025868890344427357,
 0.06371853988640781,
 0.003558902594911195,
 0.07538510582578759,
 0.0010750449968560884,
 0.007859315944754166,
 0.028815113244065202,
 0.12979189622567372,
 0.03592322863848521]

In [139]:
temp = pd.DataFrame(list(zip(col_list, FScore)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.132822
1      dit  0.000151
2      noc  0.001543
3      cbo  0.080882
4      rfc  0.238849
5     lcom  0.023099
6       ca  0.008264
7       ce  0.120234
8      npm  0.072935
9    lcom3  0.005588
10     loc  0.239752
11     dam  0.025869
12     moa  0.063719
13     mfa  0.003559
14     cam  0.075385
15      ic  0.001075
16     cbm  0.007859
17     amc  0.028815
18  max_cc  0.129792
19  avg_cc  0.035923

In [140]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
10     loc  0.239752
4      rfc  0.238849
0      wmc  0.132822
18  max_cc  0.129792
7       ce  0.120234
3      cbo  0.080882
14     cam  0.075385
8      npm  0.072935
12     moa  0.063719
19  avg_cc  0.035923

In [141]:
FS = list(temp_sort['col'][:10])
FS

['loc', 'rfc', 'wmc', 'max_cc', 'ce', 'cbo', 'cam', 'npm', 'moa', 'avg_cc']

In [142]:
X_new = df[FS]
X_new

     loc  rfc  wmc  max_cc  ce  cbo       cam  npm  moa  avg_cc
0    926   82   28      23   7   32  0.226337   24    0  2.6786
1     36    7    6       1   1    3  0.444444    4    0  0.6667
2     21    6    4       1   4    5  0.500000    2    1  0.5000
3      4    4    4       1   0    9  0.666667    4    0  1.0000
4      1    1    1       1   2    8  1.000000    1    0  1.0000
..   ...  ...  ...     ...  ..  ...       ...  ...  ...     ...
347    3    3    3       1   1   15  0.666667    3    0  1.0000
348  141   17    8       6   1   18  0.343750    8    1  1.6250
349   10   10   10       1   3   15  0.366667   10    0  1.0000
350  636  113   45       2   0   13  0.306667   45    0  1.0000
351  348   44    7       1   7   10  0.354167    4    0  0.7143

[352 rows x 10 columns]

In [143]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [144]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Support Vector Machine

In [145]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### KNeighborsClassifier

In [146]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [147]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7452830188679245
Precision :  0.16
Recall :  0.4
F1 Score :  0.22857142857142856
AUC :  0.590625

# SVM RFE 10

In [148]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [149]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=10)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [150]:
X_train = X_train.loc[:, rfe.support_]
X_train

     wmc  cbo  rfc  ca  ce  npm  loc       cam   amc  max_cc
323   10    6   30   3   4    0  290  0.360000  27.5       4
131    2    6    7   2   4    2   18  0.625000   8.0       1
148   11   43   11  35   8   11   11  0.409091   0.0       1
286    5   13   31   2  11    4  140  0.342857  26.6       1
318    5    3   15   1   2    4   50  0.500000   9.0       1
..   ...  ...  ...  ..  ..  ...  ...       ...   ...     ...
237    4    6   14   3   3    4   74  0.500000  17.0       7
31    10    9   15   3   6    8   67  0.650000   5.3       2
40     3   16   38   2   0    1  159  1.000000  52.0       1
230    4    2    6   1   1    3   23  0.666667   4.5       2
83     2    2   18   1   1    2   99  0.666667  47.5       3

[246 rows x 10 columns]

In [151]:
X_test = X_test.loc[:, rfe.support_]
X_test

     wmc  cbo  rfc  ca  ce  npm   loc       cam         amc  max_cc
333   21   30  108   1   0    7   766  0.292857   35.047619      10
285    3    6    5   3   3    1    18  0.750000    4.666667       1
14    19    8   42   2   7    3   329  0.263158   16.052632       5
50    11    4   25   3   1    7   215  0.242424   18.000000       3
167    3    6   18   2   4    2    67  0.444444   21.333333       7
..   ...  ...  ...  ..  ..  ...   ...       ...         ...     ...
351    7   10   44   4   7    4   348  0.354167   48.428571       1
145   25    6   26   5   1   25   136  0.246667    3.960000       1
77     7   10   63   2   8    5  1034  0.285714  146.714286      10
63     5    3   13   1   2    5    48  0.400000    8.400000       3
321   13   19   77   4  15   12  1090  0.253846   82.769231      14

[106 rows x 10 columns]

### RandomForest

In [152]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.25
Recall :  0.3
F1 Score :  0.2727272727272727
AUC :  0.603125

### Support Vector Machine

In [153]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### KNeighborsClassifier

In [154]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [155]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7264150943396226
Precision :  0.14814814814814814
Recall :  0.4
F1 Score :  0.21621621621621623
AUC :  0.5802083333333333

# SVM RFE 15

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [157]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=15)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [158]:
X_train = X_train.loc[:, rfe.support_]
X_train

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,moa,mfa,cam,amc,max_cc,avg_cc
323,10,6,30,27,3,4,0,0.733333,290,1,0.363636,0.360000,27.5,4,1.4000
131,2,6,7,1,2,4,2,2.000000,18,0,0.937500,0.625000,8.0,1,0.5000
148,11,43,11,55,35,8,11,2.000000,11,0,0.000000,0.409091,0.0,1,1.0000
286,5,13,31,8,2,11,4,0.625000,140,1,0.000000,0.342857,26.6,1,0.8000
318,5,3,15,10,1,2,4,2.000000,50,0,0.785714,0.500000,9.0,1,0.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,4,6,14,0,3,3,4,0.333333,74,0,0.000000,0.500000,17.0,7,2.2500
31,10,9,15,29,3,6,8,0.777778,67,1,0.000000,0.650000,5.3,2,1.0000
40,3,16,38,3,2,0,1,2.000000,159,0,0.981132,1.000000,52.0,1,0.6667
230,4,2,6,6,1,1,3,1.000000,23,1,0.000000,0.666667,4.5,2,0.7500
83,2,2,18,0,1,1,2,0.000000,99,0,0.983871,0.666667,47.5,3,1.5000

In [159]:
X_test = X_test.loc[:, rfe.support_]
X_test

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,moa,mfa,cam,amc,max_cc,avg_cc
333,21,30,108,190,1,0,7,0.794444,766,1,0.366667,0.292857,35.047619,10,1.9524
285,3,6,5,3,3,3,1,1.000000,18,1,0.800000,0.750000,4.666667,1,0.3333
14,19,8,42,99,2,7,3,0.788889,329,1,0.000000,0.263158,16.052632,5,1.5789
50,11,4,25,23,3,1,7,0.766667,215,0,0.000000,0.242424,18.000000,3,1.0909
167,3,6,18,3,2,4,2,2.000000,67,0,0.000000,0.444444,21.333333,7,3.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,7,10,44,19,4,7,4,0.916667,348,0,0.000000,0.354167,48.428571,1,0.7143
145,25,6,26,276,5,1,25,0.958333,136,1,0.000000,0.246667,3.960000,1,0.9600
77,7,10,63,21,2,8,5,2.000000,1034,0,0.000000,0.285714,146.714286,10,4.8571
63,5,3,13,4,1,2,5,0.500000,48,0,0.000000,0.400000,8.400000,3,1.2000
321,13,19,77,0,4,15,12,0.250000,1090,1,0.000000,0.253846,82.769231,14,2.8462

### RandomForest

In [160]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8584905660377359
Precision :  0.2727272727272727
Recall :  0.3
F1 Score :  0.28571428571428564
AUC :  0.6083333333333333

### Support Vector Machine

In [161]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [162]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.125
Recall :  0.1
F1 Score :  0.11111111111111112
AUC :  0.5135416666666668

### Gaussian Naive Bayes

In [163]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7641509433962265
Precision :  0.17391304347826086
Recall :  0.4
F1 Score :  0.24242424242424243
AUC :  0.6010416666666666

# MRMR 10

In [164]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [165]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [166]:
K = 10

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [167]:
selected

['loc', 'rfc', 'max_cc', 'wmc', 'ce', 'cbo', 'cam', 'moa', 'npm', 'amc']

In [168]:
X_new = X[selected]
X_new

     loc  rfc  max_cc  wmc  ce  cbo       cam  moa  npm        amc
0    926   82      23   28   7   32  0.226337    0   24  31.642857
1     36    7       1    6   1    3  0.444444    0    4   4.666667
2     21    6       1    4   4    5  0.500000    1    2   4.000000
3      4    4       1    4   0    9  0.666667    0    4   0.000000
4      1    1       1    1   2    8  1.000000    0    1   0.000000
..   ...  ...     ...  ...  ..  ...       ...  ...  ...        ...
347    3    3       1    3   1   15  0.666667    0    3   0.000000
348  141   17       6    8   1   18  0.343750    1    8  16.125000
349   10   10       1   10   3   15  0.366667    0   10   0.000000
350  636  113       2   45   0   13  0.306667    0   45  12.666667
351  348   44       1    7   7   10  0.354167    0    4  48.428571

[352 rows x 10 columns]

In [169]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [170]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Support Vector Machine

In [171]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### KNeighborsClassifier

In [172]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [173]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7264150943396226
Precision :  0.14814814814814814
Recall :  0.4
F1 Score :  0.21621621621621623
AUC :  0.5802083333333333

# MRMR 15

In [174]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [175]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [176]:
K = 15

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [177]:
selected

['loc',
 'rfc',
 'max_cc',
 'wmc',
 'ce',
 'cbo',
 'cam',
 'moa',
 'npm',
 'amc',
 'dam',
 'avg_cc',
 'cbm',
 'lcom',
 'noc']

In [178]:
X_new = X[selected]
X_new

,loc,rfc,max_cc,wmc,ce,cbo,cam,moa,npm,amc,dam,avg_cc,cbm,lcom,noc
0,926,82,23,28,7,32,0.226337,0,24,31.642857,0.166667,2.6786,0,374,0
1,36,7,1,6,1,3,0.444444,0,4,4.666667,1.000000,0.6667,0,3,2
2,21,6,1,4,4,5,0.500000,1,2,4.000000,1.000000,0.5000,0,4,0
3,4,4,1,4,0,9,0.666667,0,4,0.000000,0.000000,1.0000,0,6,0
4,1,1,1,1,2,8,1.000000,0,1,0.000000,0.000000,1.0000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,3,3,1,3,1,15,0.666667,0,3,0.000000,0.000000,1.0000,0,3,0
348,141,17,6,8,1,18,0.343750,1,8,16.125000,1.000000,1.6250,1,20,0
349,10,10,1,10,3,15,0.366667,0,10,0.000000,0.000000,1.0000,0,45,0
350,636,113,2,45,0,13,0.306667,0,45,12.666667,1.000000,1.0000,5,814,0
351,348,44,1,7,7,10,0.354167,0,4,48.428571,0.500000,0.7143,0,19,0

In [179]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [180]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8584905660377359
Precision :  0.2727272727272727
Recall :  0.3
F1 Score :  0.28571428571428564
AUC :  0.6083333333333333

### KNeighborsClassifier

In [181]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8301886792452831
Precision :  0.1
Recall :  0.1
F1 Score :  0.10000000000000002
AUC :  0.503125

### Support Vector Machine

In [182]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [183]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8301886792452831
Precision :  0.1
Recall :  0.1
F1 Score :  0.10000000000000002
AUC :  0.503125

### Gaussian Naive Bayes

In [184]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7358490566037735
Precision :  0.15384615384615385
Recall :  0.4
F1 Score :  0.2222222222222222
AUC :  0.5854166666666667

# MRMR HFS

In [185]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d + (d*(d-1)*(sum(red_FF)/len(red_FF))))**(1/2)
            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [186]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['rfc', 'noc']

In [187]:
X_new = X[FS]

In [188]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [189]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8113207547169812
Precision :  0.25
Recall :  0.5
F1 Score :  0.3333333333333333
AUC :  0.671875

### Support Vector Machine

In [190]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8679245283018868
Precision :  0.25
Recall :  0.2
F1 Score :  0.22222222222222224
AUC :  0.56875

### KNeighborsClassifier

In [191]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [192]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8207547169811321
Precision :  0.2
Recall :  0.3
F1 Score :  0.24
AUC :  0.5875

# HFS NEW

In [193]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d - (sum(red_FF)/len(red_FF)))**(1/2)

            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [194]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['rfc', 'loc']

In [195]:
X_new = X[FS]

In [196]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [197]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.26666666666666666
Recall :  0.4
F1 Score :  0.32
AUC :  0.6427083333333333

### Support Vector Machine

In [198]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8490566037735849
Precision :  0.2857142857142857
Recall :  0.4
F1 Score :  0.3333333333333333
AUC :  0.6479166666666667

### KNeighborsClassifier

In [199]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.839622641509434
Precision :  0.23076923076923078
Recall :  0.3
F1 Score :  0.2608695652173913
AUC :  0.5979166666666668

### Gaussian Naive Bayes

In [200]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7924528301886793
Precision :  0.2
Recall :  0.4
F1 Score :  0.26666666666666666
AUC :  0.6166666666666667