In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('jedit-4.0.csv')
df

,id,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,defects
0,1,6,8,0,10,22,15,1,10,4,...,0.000000,0,0.994206,0.333333,1,7,20.333333,5,2.1667,0
1,2,12,6,0,7,39,28,3,6,1,...,1.000000,2,0.983655,0.500000,1,3,45.416667,2,1.1667,1
2,3,14,7,0,28,108,69,3,28,8,...,1.000000,2,0.980480,0.174603,0,0,50.571429,9,2.1429,2
3,4,2,2,0,2,6,1,1,2,2,...,0.000000,0,0.875000,0.625000,0,0,41.500000,5,2.5000,0
4,5,5,6,0,5,28,0,2,4,1,...,1.000000,0,0.993994,0.500000,2,4,64.000000,3,1.6000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,302,5,1,0,9,14,0,8,2,0,...,1.000000,0,0.000000,0.466667,0,0,15.200000,4,2.0000,1
302,303,6,3,0,2,20,15,2,0,4,...,0.000000,0,0.850000,0.500000,1,1,28.666667,14,2.8333,0
303,304,11,1,0,39,25,0,38,2,11,...,1.000000,0,0.000000,0.484848,0,0,11.181818,2,1.1818,0
304,305,14,5,0,19,67,55,10,16,8,...,0.833333,1,0.980480,0.257143,3,12,24.357143,10,1.8571,2
305,306,6,2,0,16,46,15,3,13,6,...,0.000000,0,0.782609,0.229167,1,1,45.500000,1,0.8333,0

In [7]:
df.drop(['id'], axis=1, inplace=True)

In [8]:
df['defects'].unique()

array([ 0,  1,  2, 18, 23,  7, 14,  3,  4,  9, 15,  5,  6], dtype=int64)

In [9]:
df['defects'].replace([ 2, 18, 23,  7, 14,  3,  4,  9, 15,  5,  6], 1, inplace=True)
df['defects'].unique()

array([0, 1], dtype=int64)

In [10]:
df = df.rename({'defects':'class'}, axis=1)
df

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,6,8,0,10,22,15,1,10,4,2.000000,...,0.000000,0,0.994206,0.333333,1,7,20.333333,5,2.1667,0
1,12,6,0,7,39,28,3,6,1,0.397727,...,1.000000,2,0.983655,0.500000,1,3,45.416667,2,1.1667,1
2,14,7,0,28,108,69,3,28,8,0.869231,...,1.000000,2,0.980480,0.174603,0,0,50.571429,9,2.1429,1
3,2,2,0,2,6,1,1,2,2,2.000000,...,0.000000,0,0.875000,0.625000,0,0,41.500000,5,2.5000,0
4,5,6,0,5,28,0,2,4,1,0.708333,...,1.000000,0,0.993994,0.500000,2,4,64.000000,3,1.6000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,5,1,0,9,14,0,8,2,0,0.000000,...,1.000000,0,0.000000,0.466667,0,0,15.200000,4,2.0000,1
302,6,3,0,2,20,15,2,0,4,1.120000,...,0.000000,0,0.850000,0.500000,1,1,28.666667,14,2.8333,0
303,11,1,0,39,25,0,38,2,11,0.000000,...,1.000000,0,0.000000,0.484848,0,0,11.181818,2,1.1818,0
304,14,5,0,19,67,55,10,16,8,0.820513,...,0.833333,1,0.980480,0.257143,3,12,24.357143,10,1.8571,1
305,6,2,0,16,46,15,3,13,6,2.000000,...,0.000000,0,0.782609,0.229167,1,1,45.500000,1,0.8333,0

In [11]:
df[df['class'] == 0]

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,6,8,0,10,22,15,1,10,4,2.00,...,0.0,0,0.994206,0.333333,1,7,20.333333,5,2.1667,0
3,2,2,0,2,6,1,1,2,2,2.00,...,0.0,0,0.875000,0.625000,0,0,41.500000,5,2.5000,0
5,2,2,0,1,4,1,0,1,2,2.00,...,0.0,0,0.750000,0.750000,1,1,7.000000,2,1.0000,0
6,2,8,0,11,33,1,3,11,2,2.00,...,0.0,0,0.998836,0.750000,2,4,102.000000,16,8.0000,0
8,7,1,0,36,7,21,36,0,7,2.00,...,0.0,0,0.000000,0.523810,0,0,0.000000,1,1.0000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,5,1,0,8,5,10,8,1,5,2.00,...,0.0,0,0.000000,0.600000,0,0,0.000000,1,1.0000,0
300,2,1,0,2,2,1,2,1,2,2.00,...,0.0,0,0.000000,0.750000,0,0,0.000000,1,1.0000,0
302,6,3,0,2,20,15,2,0,4,1.12,...,0.0,0,0.850000,0.500000,1,1,28.666667,14,2.8333,0
303,11,1,0,39,25,0,38,2,11,0.00,...,1.0,0,0.000000,0.484848,0,0,11.181818,2,1.1818,0
305,6,2,0,16,46,15,3,13,6,2.00,...,0.0,0,0.782609,0.229167,1,1,45.500000,1,0.8333,0

In [12]:
X = df.drop(['class'], axis=1)
X

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc
0,6,8,0,10,22,15,1,10,4,2.000000,128,0.000000,0,0.994206,0.333333,1,7,20.333333,5,2.1667
1,12,6,0,7,39,28,3,6,1,0.397727,573,1.000000,2,0.983655,0.500000,1,3,45.416667,2,1.1667
2,14,7,0,28,108,69,3,28,8,0.869231,732,1.000000,2,0.980480,0.174603,0,0,50.571429,9,2.1429
3,2,2,0,2,6,1,1,2,2,2.000000,85,0.000000,0,0.875000,0.625000,0,0,41.500000,5,2.5000
4,5,6,0,5,28,0,2,4,1,0.708333,337,1.000000,0,0.993994,0.500000,2,4,64.000000,3,1.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,5,1,0,9,14,0,8,2,0,0.000000,82,1.000000,0,0.000000,0.466667,0,0,15.200000,4,2.0000
302,6,3,0,2,20,15,2,0,4,1.120000,183,0.000000,0,0.850000,0.500000,1,1,28.666667,14,2.8333
303,11,1,0,39,25,0,38,2,11,0.000000,135,1.000000,0,0.000000,0.484848,0,0,11.181818,2,1.1818
304,14,5,0,19,67,55,10,16,8,0.820513,361,0.833333,1,0.980480,0.257143,3,12,24.357143,10,1.8571
305,6,2,0,16,46,15,3,13,6,2.000000,279,0.000000,0,0.782609,0.229167,1,1,45.500000,1,0.8333

In [13]:
Y = df['class']
Y

0      0
1      1
2      1
3      0
4      1
      ..
301    1
302    0
303    0
304    1
305    0
Name: class, Length: 306, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

# All Features

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

### Support Vector Machine

In [16]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### Support Vector Machine

In [17]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### KNeighborsClassifier

In [18]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.782608695652174
Precision :  0.6111111111111112
Recall :  0.4583333333333333
F1 Score :  0.5238095238095238
AUC :  0.6776960784313725

### Gaussian Naive Bayes

In [19]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.6153846153846154
Recall :  0.3333333333333333
F1 Score :  0.43243243243243246
AUC :  0.6299019607843137

# PEARSON CORRELATION

In [22]:
cor = df.corr()
cor_target = abs(cor['class'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.3]
relevant_features

cbo      0.307222
rfc      0.346045
ce       0.348119
dam      0.338494
moa      0.329407
class    1.000000
Name: class, dtype: float64

In [23]:
X_new = df[['cbo', 'rfc', 'ce', 'dam', 'moa']]
X_new

     cbo  rfc  ce       dam  moa
0     10   22  10  0.000000    0
1      7   39   6  1.000000    2
2     28  108  28  1.000000    2
3      2    6   2  0.000000    0
4      5   28   4  1.000000    0
..   ...  ...  ..       ...  ...
301    9   14   2  1.000000    0
302    2   20   0  0.000000    0
303   39   25   2  1.000000    0
304   19   67  16  0.833333    1
305   16   46  13  0.000000    0

[306 rows x 5 columns]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [25]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.5555555555555556
Recall :  0.4166666666666667
F1 Score :  0.4761904761904762
AUC :  0.6495098039215687

### Support Vector Machine

In [26]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.42857142857142855
Recall :  0.125
F1 Score :  0.19354838709677416
AUC :  0.5330882352941176

### KNeighborsClassifier

In [27]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.2916666666666667
F1 Score :  0.3684210526315789
AUC :  0.5943627450980393

### Gaussian Naive Bayes

In [28]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.6
Recall :  0.375
F1 Score :  0.4615384615384615
AUC :  0.6433823529411765

# INFORMATION GAIN 10

In [29]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.11619161, 0.05024121, 0.01130858, 0.05149915, 0.07687056,
       0.06366096, 0.03526023, 0.05704446, 0.07174917, 0.0802087 ,
       0.10163981, 0.08111644, 0.13643794, 0.07776346, 0.07390447,
       0.        , 0.        , 0.02082535, 0.0751377 , 0.04433502])

In [30]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [31]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.116192
1      dit  0.050241
2      noc  0.011309
3      cbo  0.051499
4      rfc  0.076871
5     lcom  0.063661
6       ca  0.035260
7       ce  0.057044
8      npm  0.071749
9    lcom3  0.080209
10     loc  0.101640
11     dam  0.081116
12     moa  0.136438
13     mfa  0.077763
14     cam  0.073904
15      ic  0.000000
16     cbm  0.000000
17     amc  0.020825
18  max_cc  0.075138
19  avg_cc  0.044335

In [32]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
12     moa  0.136438
0      wmc  0.116192
10     loc  0.101640
11     dam  0.081116
9    lcom3  0.080209
13     mfa  0.077763
4      rfc  0.076871
18  max_cc  0.075138
14     cam  0.073904
8      npm  0.071749

In [33]:
FS = list(temp_sort['col'][:10])
FS

['moa', 'wmc', 'loc', 'dam', 'lcom3', 'mfa', 'rfc', 'max_cc', 'cam', 'npm']

In [34]:
X_new = df[FS]
X_new

     moa  wmc  loc       dam     lcom3       mfa  rfc  max_cc       cam  npm
0      0    6  128  0.000000  2.000000  0.994206   22       5  0.333333    4
1      2   12  573  1.000000  0.397727  0.983655   39       2  0.500000    1
2      2   14  732  1.000000  0.869231  0.980480  108       9  0.174603    8
3      0    2   85  0.000000  2.000000  0.875000    6       5  0.625000    2
4      0    5  337  1.000000  0.708333  0.993994   28       3  0.500000    1
..   ...  ...  ...       ...       ...       ...  ...     ...       ...  ...
301    0    5   82  1.000000  0.000000  0.000000   14       4  0.466667    0
302    0    6  183  0.000000  1.120000  0.850000   20      14  0.500000    4
303    0   11  135  1.000000  0.000000  0.000000   25       2  0.484848   11
304    1   14  361  0.833333  0.820513  0.980480   67      10  0.257143    8
305    0    6  279  0.000000  2.000000  0.782609   46       1  0.229167    6

[306 rows x 10 columns]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [36]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8043478260869565
Precision :  0.6875
Recall :  0.4583333333333333
F1 Score :  0.5499999999999999
AUC :  0.6924019607843137

### Support Vector Machine

In [37]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.6
Recall :  0.25
F1 Score :  0.35294117647058826
AUC :  0.5955882352941176

### KNeighborsClassifier

In [38]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7065217391304348
Precision :  0.38461538461538464
Recall :  0.20833333333333334
F1 Score :  0.2702702702702703
AUC :  0.5453431372549019

### Gaussian Naive Bayes

In [39]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.6153846153846154
Recall :  0.3333333333333333
F1 Score :  0.43243243243243246
AUC :  0.6299019607843137

# INFORMATION GAIN 15

In [40]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.08131951, 0.08762188, 0.        , 0.04930056, 0.07796296,
       0.06751595, 0.01620935, 0.04659171, 0.07225727, 0.06251227,
       0.09623598, 0.07554071, 0.09001941, 0.10446076, 0.07672759,
       0.        , 0.02238802, 0.02040795, 0.07023718, 0.03088516])

In [41]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [42]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.081320
1      dit  0.087622
2      noc  0.000000
3      cbo  0.049301
4      rfc  0.077963
5     lcom  0.067516
6       ca  0.016209
7       ce  0.046592
8      npm  0.072257
9    lcom3  0.062512
10     loc  0.096236
11     dam  0.075541
12     moa  0.090019
13     mfa  0.104461
14     cam  0.076728
15      ic  0.000000
16     cbm  0.022388
17     amc  0.020408
18  max_cc  0.070237
19  avg_cc  0.030885

In [43]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:15]

       col     score
13     mfa  0.104461
10     loc  0.096236
12     moa  0.090019
1      dit  0.087622
0      wmc  0.081320
4      rfc  0.077963
14     cam  0.076728
11     dam  0.075541
8      npm  0.072257
18  max_cc  0.070237
5     lcom  0.067516
9    lcom3  0.062512
3      cbo  0.049301
7       ce  0.046592
19  avg_cc  0.030885

In [44]:
FS = list(temp_sort['col'][:15])
FS

['mfa',
 'loc',
 'moa',
 'dit',
 'wmc',
 'rfc',
 'cam',
 'dam',
 'npm',
 'max_cc',
 'lcom',
 'lcom3',
 'cbo',
 'ce',
 'avg_cc']

In [45]:
X_new = df[FS]
X_new

,mfa,loc,moa,dit,wmc,rfc,cam,dam,npm,max_cc,lcom,lcom3,cbo,ce,avg_cc
0,0.994206,128,0,8,6,22,0.333333,0.000000,4,5,15,2.000000,10,10,2.1667
1,0.983655,573,2,6,12,39,0.500000,1.000000,1,2,28,0.397727,7,6,1.1667
2,0.980480,732,2,7,14,108,0.174603,1.000000,8,9,69,0.869231,28,28,2.1429
3,0.875000,85,0,2,2,6,0.625000,0.000000,2,5,1,2.000000,2,2,2.5000
4,0.993994,337,0,6,5,28,0.500000,1.000000,1,3,0,0.708333,5,4,1.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.000000,82,0,1,5,14,0.466667,1.000000,0,4,0,0.000000,9,2,2.0000
302,0.850000,183,0,3,6,20,0.500000,0.000000,4,14,15,1.120000,2,0,2.8333
303,0.000000,135,0,1,11,25,0.484848,1.000000,11,2,0,0.000000,39,2,1.1818
304,0.980480,361,1,5,14,67,0.257143,0.833333,8,10,55,0.820513,19,16,1.8571
305,0.782609,279,0,2,6,46,0.229167,0.000000,6,1,15,2.000000,16,13,0.8333

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [47]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.5789473684210527
Recall :  0.4583333333333333
F1 Score :  0.5116279069767442
AUC :  0.6703431372549019

### Support Vector Machine

In [48]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### KNeighborsClassifier

In [49]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.6
Recall :  0.375
F1 Score :  0.4615384615384615
AUC :  0.6433823529411765

### Gaussian Naive Bayes

In [50]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.6
Recall :  0.25
F1 Score :  0.35294117647058826
AUC :  0.5955882352941176

# FISHER SCORE

In [51]:
FScore = []

for m in  range(len(col_list)):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        FScore.append(inter_class / intra_class)

FScore

[0.03067398035479066,
 0.006082152625005491,
 0.0035483966798389257,
 0.10422277426835697,
 0.1360373022686943,
 0.030517173591666974,
 0.0750567010868514,
 0.1378979519716103,
 0.07071419777635146,
 0.04564900448477029,
 0.01436107065737221,
 0.12940494574231604,
 0.12171668671357813,
 0.0029950396404390687,
 0.07820807807635952,
 0.01257952656781769,
 0.035805508884948954,
 0.008968023656117532,
 0.09328445624478313,
 0.03728338354067862]

In [52]:
temp = pd.DataFrame(list(zip(col_list, FScore)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.030674
1      dit  0.006082
2      noc  0.003548
3      cbo  0.104223
4      rfc  0.136037
5     lcom  0.030517
6       ca  0.075057
7       ce  0.137898
8      npm  0.070714
9    lcom3  0.045649
10     loc  0.014361
11     dam  0.129405
12     moa  0.121717
13     mfa  0.002995
14     cam  0.078208
15      ic  0.012580
16     cbm  0.035806
17     amc  0.008968
18  max_cc  0.093284
19  avg_cc  0.037283

In [53]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
7       ce  0.137898
4      rfc  0.136037
11     dam  0.129405
12     moa  0.121717
3      cbo  0.104223
18  max_cc  0.093284
14     cam  0.078208
6       ca  0.075057
8      npm  0.070714
9    lcom3  0.045649

In [54]:
FS = list(temp_sort['col'][:10])
FS

['ce', 'rfc', 'dam', 'moa', 'cbo', 'max_cc', 'cam', 'ca', 'npm', 'lcom3']

In [55]:
X_new = df[FS]
X_new

     ce  rfc       dam  moa  cbo  max_cc       cam  ca  npm     lcom3
0    10   22  0.000000    0   10       5  0.333333   1    4  2.000000
1     6   39  1.000000    2    7       2  0.500000   3    1  0.397727
2    28  108  1.000000    2   28       9  0.174603   3    8  0.869231
3     2    6  0.000000    0    2       5  0.625000   1    2  2.000000
4     4   28  1.000000    0    5       3  0.500000   2    1  0.708333
..   ..  ...       ...  ...  ...     ...       ...  ..  ...       ...
301   2   14  1.000000    0    9       4  0.466667   8    0  0.000000
302   0   20  0.000000    0    2      14  0.500000   2    4  1.120000
303   2   25  1.000000    0   39       2  0.484848  38   11  0.000000
304  16   67  0.833333    1   19      10  0.257143  10    8  0.820513
305  13   46  0.000000    0   16       1  0.229167   3    6  2.000000

[306 rows x 10 columns]

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [57]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.782608695652174
Precision :  0.6111111111111112
Recall :  0.4583333333333333
F1 Score :  0.5238095238095238
AUC :  0.6776960784313725

### Support Vector Machine

In [58]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.4444444444444444
Recall :  0.16666666666666666
F1 Score :  0.24242424242424243
AUC :  0.5465686274509804

### KNeighborsClassifier

In [59]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.782608695652174
Precision :  0.625
Recall :  0.4166666666666667
F1 Score :  0.5
AUC :  0.6642156862745099

### Gaussian Naive Bayes

In [60]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.46153846153846156
Recall :  0.25
F1 Score :  0.32432432432432434
AUC :  0.5735294117647058

# SVM RFE 10

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [62]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=10)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [63]:
X_train = X_train.loc[:, rfe.support_]
X_train

     wmc  rfc  lcom  npm   loc  moa       cam        amc  max_cc  avg_cc
255    5   18     8    5   173    2  0.366667  32.400000       7  2.6000
216   12   36    24    7   253    0  0.395833  19.833333       4  1.5833
200    3   17     1    3   307    0  1.000000  98.000000       5  2.0000
147    4   22     4    3   118    0  0.300000  28.000000       5  2.2500
131    5   17     0    5    96    1  0.533333  16.600000       2  1.0000
..   ...  ...   ...  ...   ...  ...       ...        ...     ...     ...
237   47  109  1019   26  2553    2  0.230072  53.042553      11  1.7660
31    21   53     0   21  1726    3  0.251701  80.857143      31  8.5714
40     3    5     3    0    20    0  0.466667   5.666667       1  0.6667
230    4    5     6    4    11    0  0.750000   1.750000       1  0.7500
83    17   37   100   16   679    0  0.323529  38.352941      12  2.0000

[214 rows x 10 columns]

In [64]:
X_test = X_test.loc[:, rfe.support_]
X_test

     wmc  rfc  lcom  npm  loc  moa       cam        amc  max_cc  avg_cc
275    2    6     1    1   30    0  0.625000  14.000000       1  0.5000
127    2   19     1    1   89    0  0.625000  43.500000       1  0.5000
14    14   95    21    8  973    1  0.589744  68.071429      11  2.0714
134    3   33     3    3  180    0  0.555556  59.000000       1  0.6667
168   18  131   113    6  844    0  0.194444  45.333333       8  1.6111
..   ...  ...   ...  ...  ...  ...       ...        ...     ...     ...
107    6   46     9    3  299    0  0.388889  48.333333       1  0.8333
167    2    7     1    1   80    0  0.625000  38.500000       1  0.5000
280    2    4     1    2    9    0  0.750000   3.500000       0  0.0000
47     1    2     0    1    5    0  1.000000   4.000000       0  0.0000
205    6   14     3    5   93    0  0.444444  14.000000       1  0.8333

[92 rows x 10 columns]

### RandomForest

In [65]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7934782608695652
Precision :  0.6470588235294118
Recall :  0.4583333333333333
F1 Score :  0.5365853658536585
AUC :  0.6850490196078431

### Support Vector Machine

In [66]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### KNeighborsClassifier

In [67]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.5882352941176471
Recall :  0.4166666666666667
F1 Score :  0.48780487804878053
AUC :  0.6568627450980393

### Gaussian Naive Bayes

In [68]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.42857142857142855
Recall :  0.125
F1 Score :  0.19354838709677416
AUC :  0.5330882352941176

# SVM RFE 15

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [70]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=15)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [71]:
X_train = X_train.loc[:, rfe.support_]
X_train

,wmc,cbo,rfc,lcom,ce,npm,lcom3,loc,dam,moa,mfa,cam,amc,max_cc,avg_cc
255,5,4,18,8,4,5,0.375000,173,1.000000,2,0.818182,0.366667,32.400000,7,2.6000
216,12,5,36,24,2,7,0.818182,253,0.666667,0,0.592593,0.395833,19.833333,4,1.5833
200,3,3,17,1,2,3,0.500000,307,1.000000,0,0.996988,1.000000,98.000000,5,2.0000
147,4,6,22,4,6,3,0.833333,118,1.000000,0,0.000000,0.300000,28.000000,5,2.2500
131,5,6,17,0,3,5,0.656250,96,0.000000,1,0.000000,0.533333,16.600000,2,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,47,38,109,1019,25,26,0.944816,2553,0.461538,2,0.148936,0.230072,53.042553,11,1.7660
31,21,14,53,0,7,21,0.492857,1726,1.000000,3,0.000000,0.251701,80.857143,31,8.5714
40,3,4,5,3,3,0,2.000000,20,0.000000,0,0.777778,0.466667,5.666667,1,0.6667
230,4,9,5,6,0,4,2.000000,11,0.000000,0,0.000000,0.750000,1.750000,1,0.7500
83,17,2,37,100,0,16,0.700000,679,0.800000,0,0.000000,0.323529,38.352941,12,2.0000

In [72]:
X_test = X_test.loc[:, rfe.support_]
X_test

,wmc,cbo,rfc,lcom,ce,npm,lcom3,loc,dam,moa,mfa,cam,amc,max_cc,avg_cc
275,2,10,6,1,5,1,2.000000,30,0.0,0,0.947368,0.625000,14.000000,1,0.5000
127,2,12,19,1,11,1,2.000000,89,0.0,0,0.947368,0.625000,43.500000,1,0.5000
14,14,14,95,21,9,8,0.692308,973,1.0,1,0.853333,0.589744,68.071429,11,2.0714
134,3,6,33,3,4,3,2.000000,180,0.0,0,0.996947,0.555556,59.000000,1,0.6667
168,18,22,131,113,22,6,0.764706,844,1.0,0,0.977273,0.194444,45.333333,8,1.6111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,6,8,46,9,8,3,0.800000,299,1.0,0,0.992401,0.388889,48.333333,1,0.8333
167,2,10,7,1,9,1,1.000000,80,0.0,0,0.947368,0.625000,38.500000,1,0.5000
280,2,7,4,1,0,2,2.000000,9,0.0,0,1.000000,0.750000,3.500000,0,0.0000
47,1,17,2,0,0,1,2.000000,5,0.0,0,1.000000,1.000000,4.000000,0,0.0000
205,6,16,14,3,8,5,0.666667,93,1.0,0,0.782609,0.444444,14.000000,1,0.8333

### RandomForest

In [73]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8043478260869565
Precision :  0.6666666666666666
Recall :  0.5
F1 Score :  0.5714285714285715
AUC :  0.7058823529411765

### Support Vector Machine

In [74]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### KNeighborsClassifier

In [75]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.5882352941176471
Recall :  0.4166666666666667
F1 Score :  0.48780487804878053
AUC :  0.6568627450980393

### Gaussian Naive Bayes

In [76]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.6
Recall :  0.25
F1 Score :  0.35294117647058826
AUC :  0.5955882352941176

# MRMR 10

In [77]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [78]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [79]:
K = 10

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [80]:
selected

['ce', 'dam', 'moa', 'max_cc', 'rfc', 'cbo', 'cbm', 'cam', 'ca', 'lcom3']

In [81]:
X_new = X[selected]
X_new

     ce       dam  moa  max_cc  rfc  cbo  cbm       cam  ca     lcom3
0    10  0.000000    0       5   22   10    7  0.333333   1  2.000000
1     6  1.000000    2       2   39    7    3  0.500000   3  0.397727
2    28  1.000000    2       9  108   28    0  0.174603   3  0.869231
3     2  0.000000    0       5    6    2    0  0.625000   1  2.000000
4     4  1.000000    0       3   28    5    4  0.500000   2  0.708333
..   ..       ...  ...     ...  ...  ...  ...       ...  ..       ...
301   2  1.000000    0       4   14    9    0  0.466667   8  0.000000
302   0  0.000000    0      14   20    2    1  0.500000   2  1.120000
303   2  1.000000    0       2   25   39    0  0.484848  38  0.000000
304  16  0.833333    1      10   67   19   12  0.257143  10  0.820513
305  13  0.000000    0       1   46   16    1  0.229167   3  2.000000

[306 rows x 10 columns]

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [83]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.55
Recall :  0.4583333333333333
F1 Score :  0.5
AUC :  0.6629901960784313

### Support Vector Machine

In [84]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7391304347826086
Precision :  0.5
Recall :  0.16666666666666666
F1 Score :  0.25
AUC :  0.553921568627451

### KNeighborsClassifier

In [85]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7934782608695652
Precision :  0.6470588235294118
Recall :  0.4583333333333333
F1 Score :  0.5365853658536585
AUC :  0.6850490196078431

### Gaussian Naive Bayes

In [86]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8043478260869565
Precision :  0.6666666666666666
Recall :  0.5
F1 Score :  0.5714285714285715
AUC :  0.7058823529411765

# MRMR 15

In [87]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [88]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [89]:
K = 15

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [90]:
selected

['ce',
 'dam',
 'moa',
 'max_cc',
 'rfc',
 'cbo',
 'cbm',
 'cam',
 'ca',
 'lcom3',
 'npm',
 'avg_cc',
 'ic',
 'lcom',
 'amc']

In [91]:
X_new = X[selected]
X_new

,ce,dam,moa,max_cc,rfc,cbo,cbm,cam,ca,lcom3,npm,avg_cc,ic,lcom,amc
0,10,0.000000,0,5,22,10,7,0.333333,1,2.000000,4,2.1667,1,15,20.333333
1,6,1.000000,2,2,39,7,3,0.500000,3,0.397727,1,1.1667,1,28,45.416667
2,28,1.000000,2,9,108,28,0,0.174603,3,0.869231,8,2.1429,0,69,50.571429
3,2,0.000000,0,5,6,2,0,0.625000,1,2.000000,2,2.5000,0,1,41.500000
4,4,1.000000,0,3,28,5,4,0.500000,2,0.708333,1,1.6000,2,0,64.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2,1.000000,0,4,14,9,0,0.466667,8,0.000000,0,2.0000,0,0,15.200000
302,0,0.000000,0,14,20,2,1,0.500000,2,1.120000,4,2.8333,1,15,28.666667
303,2,1.000000,0,2,25,39,0,0.484848,38,0.000000,11,1.1818,0,0,11.181818
304,16,0.833333,1,10,67,19,12,0.257143,10,0.820513,8,1.8571,3,55,24.357143
305,13,0.000000,0,1,46,16,1,0.229167,3,2.000000,6,0.8333,1,15,45.500000

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [93]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.55
Recall :  0.4583333333333333
F1 Score :  0.5
AUC :  0.6629901960784313

### KNeighborsClassifier

In [94]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7065217391304348
Precision :  0.38461538461538464
Recall :  0.20833333333333334
F1 Score :  0.2702702702702703
AUC :  0.5453431372549019

### Support Vector Machine

In [95]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.717391304347826
Precision :  0.0
Recall :  0.0
F1 Score :  0.0
AUC :  0.4852941176470588

### KNeighborsClassifier

In [96]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7065217391304348
Precision :  0.38461538461538464
Recall :  0.20833333333333334
F1 Score :  0.2702702702702703
AUC :  0.5453431372549019

### Gaussian Naive Bayes

In [97]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7717391304347826
Precision :  0.6153846153846154
Recall :  0.3333333333333333
F1 Score :  0.43243243243243246
AUC :  0.6299019607843137

# MRMR HFS

In [98]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d + (d*(d-1)*(sum(red_FF)/len(red_FF))))**(1/2)
            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [99]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['dam', 'noc', 'lcom']

In [100]:
X_new = X[FS]

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [102]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7608695652173914
Precision :  0.625
Recall :  0.20833333333333334
F1 Score :  0.3125
AUC :  0.5821078431372549

### Support Vector Machine

In [103]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.717391304347826
Precision :  0.0
Recall :  0.0
F1 Score :  0.0
AUC :  0.4852941176470588

### KNeighborsClassifier

In [104]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7934782608695652
Precision :  0.7777777777777778
Recall :  0.2916666666666667
F1 Score :  0.42424242424242425
AUC :  0.6311274509803921

### Gaussian Naive Bayes

In [105]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.0
Recall :  0.0
F1 Score :  0.0
AUC :  0.49264705882352944

# HFS NEW

In [106]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d - (sum(red_FF)/len(red_FF)))**(1/2)

            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [107]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['moa', 'rfc', 'ce']

In [108]:
X_new = X[FS]

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [110]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.4666666666666667
Recall :  0.2916666666666667
F1 Score :  0.35897435897435903
AUC :  0.5870098039215687

### Support Vector Machine

In [111]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7282608695652174
Precision :  0.42857142857142855
Recall :  0.125
F1 Score :  0.19354838709677416
AUC :  0.5330882352941176

### KNeighborsClassifier

In [112]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.717391304347826
Precision :  0.4444444444444444
Recall :  0.3333333333333333
F1 Score :  0.380952380952381
AUC :  0.5931372549019608

### Gaussian Naive Bayes

In [113]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.782608695652174
Precision :  0.6428571428571429
Recall :  0.375
F1 Score :  0.4736842105263159
AUC :  0.6507352941176471