In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('log4j-1.csv')
df

,id,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,defects
0,1,4,4,0,3,12,6,2,1,4,...,0.000000,0,0.953488,0.357143,1,3,23.750000,3,1.000,0
1,2,2,1,0,0,3,1,0,0,2,...,0.000000,0,0.000000,0.500000,0,0,2.000000,1,0.500,0
2,3,8,1,0,6,22,0,3,3,8,...,1.000000,0,0.000000,0.406250,0,0,20.875000,5,3.125,0
3,4,8,2,1,7,24,12,1,6,8,...,0.555556,0,0.533333,0.333333,0,0,20.250000,7,2.250,0
4,5,10,1,5,34,13,45,32,2,9,...,0.000000,0,0.000000,0.407407,0,0,1.600000,1,0.800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,131,1,4,0,2,3,0,1,1,0,...,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.000,0
131,132,2,2,0,3,16,0,1,3,1,...,0.000000,1,0.983871,0.666667,0,0,23.500000,2,1.000,0
132,133,5,2,0,3,11,0,1,2,4,...,0.000000,1,0.800000,0.533333,1,1,6.200000,1,0.800,0
133,134,7,1,0,2,26,17,0,2,2,...,0.000000,1,0.000000,0.277778,0,0,17.428571,2,1.000,0
134,135,2,3,0,4,6,1,1,4,1,...,0.000000,0,0.984848,0.750000,1,1,6.000000,1,0.500,0

In [7]:
df.drop(['id'], axis=1, inplace=True)

In [8]:
df['defects'].unique()

array([0, 2, 1, 3, 9, 5], dtype=int64)

In [9]:
df['defects'].replace([2, 1, 3, 9, 5], 1, inplace=True)
df['defects'].unique()

array([0, 1], dtype=int64)

In [10]:
df = df.rename({'defects':'class'}, axis=1)
df

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,4,4,0,3,12,6,2,1,4,2.000000,...,0.000000,0,0.953488,0.357143,1,3,23.750000,3,1.000,0
1,2,1,0,0,3,1,0,0,2,2.000000,...,0.000000,0,0.000000,0.500000,0,0,2.000000,1,0.500,0
2,8,1,0,6,22,0,3,3,8,0.142857,...,1.000000,0,0.000000,0.406250,0,0,20.875000,5,3.125,0
3,8,2,1,7,24,12,1,6,8,0.936508,...,0.555556,0,0.533333,0.333333,0,0,20.250000,7,2.250,0
4,10,1,5,34,13,45,32,2,9,1.000000,...,0.000000,0,0.000000,0.407407,0,0,1.600000,1,0.800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,1,4,0,2,3,0,1,1,0,2.000000,...,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.000,0
131,2,2,0,3,16,0,1,3,1,0.000000,...,0.000000,1,0.983871,0.666667,0,0,23.500000,2,1.000,0
132,5,2,0,3,11,0,1,2,4,0.250000,...,0.000000,1,0.800000,0.533333,1,1,6.200000,1,0.800,0
133,7,1,0,2,26,17,0,2,2,0.666667,...,0.000000,1,0.000000,0.277778,0,0,17.428571,2,1.000,0
134,2,3,0,4,6,1,1,4,1,2.000000,...,0.000000,0,0.984848,0.750000,1,1,6.000000,1,0.500,0

In [11]:
df[df['class'] == 0]

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,class
0,4,4,0,3,12,6,2,1,4,2.000000,...,0.000000,0,0.953488,0.357143,1,3,23.750000,3,1.000,0
1,2,1,0,0,3,1,0,0,2,2.000000,...,0.000000,0,0.000000,0.500000,0,0,2.000000,1,0.500,0
2,8,1,0,6,22,0,3,3,8,0.142857,...,1.000000,0,0.000000,0.406250,0,0,20.875000,5,3.125,0
3,8,2,1,7,24,12,1,6,8,0.936508,...,0.555556,0,0.533333,0.333333,0,0,20.250000,7,2.250,0
4,10,1,5,34,13,45,32,2,9,1.000000,...,0.000000,0,0.000000,0.407407,0,0,1.600000,1,0.800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,1,4,0,2,3,0,1,1,0,2.000000,...,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.000,0
131,2,2,0,3,16,0,1,3,1,0.000000,...,0.000000,1,0.983871,0.666667,0,0,23.500000,2,1.000,0
132,5,2,0,3,11,0,1,2,4,0.250000,...,0.000000,1,0.800000,0.533333,1,1,6.200000,1,0.800,0
133,7,1,0,2,26,17,0,2,2,0.666667,...,0.000000,1,0.000000,0.277778,0,0,17.428571,2,1.000,0
134,2,3,0,4,6,1,1,4,1,2.000000,...,0.000000,0,0.984848,0.750000,1,1,6.000000,1,0.500,0

In [12]:
X = df.drop(['class'], axis=1)
X

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc
0,4,4,0,3,12,6,2,1,4,2.000000,99,0.000000,0,0.953488,0.357143,1,3,23.750000,3,1.000
1,2,1,0,0,3,1,0,0,2,2.000000,6,0.000000,0,0.000000,0.500000,0,0,2.000000,1,0.500
2,8,1,0,6,22,0,3,3,8,0.142857,176,1.000000,0,0.000000,0.406250,0,0,20.875000,5,3.125
3,8,2,1,7,24,12,1,6,8,0.936508,179,0.555556,0,0.533333,0.333333,0,0,20.250000,7,2.250
4,10,1,5,34,13,45,32,2,9,1.000000,28,0.000000,0,0.000000,0.407407,0,0,1.600000,1,0.800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,1,4,0,2,3,0,1,1,0,2.000000,7,0.000000,0,1.000000,1.000000,0,0,6.000000,0,0.000
131,2,2,0,3,16,0,1,3,1,0.000000,51,0.000000,1,0.983871,0.666667,0,0,23.500000,2,1.000
132,5,2,0,3,11,0,1,2,4,0.250000,37,0.000000,1,0.800000,0.533333,1,1,6.200000,1,0.800
133,7,1,0,2,26,17,0,2,2,0.666667,131,0.000000,1,0.000000,0.277778,0,0,17.428571,2,1.000
134,2,3,0,4,6,1,1,4,1,2.000000,14,0.000000,0,0.984848,0.750000,1,1,6.000000,1,0.500

In [13]:
Y = df['class']
Y

0      0
1      0
2      0
3      0
4      0
      ..
130    0
131    0
132    0
133    0
134    0
Name: class, Length: 135, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

# All Features

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

### Support Vector Machine

In [16]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Support Vector Machine

In [17]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [18]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [19]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  0.8333333333333334
Recall :  0.45454545454545453
F1 Score :  0.5882352941176471
AUC :  0.7106060606060606

# PEARSON CORRELATION

In [21]:
cor = df.corr()
cor_target = abs(cor['class'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.4]
relevant_features

wmc       0.486779
cbo       0.487373
rfc       0.451254
ce        0.435358
npm       0.449511
loc       0.454826
max_cc    0.427793
class     1.000000
Name: class, dtype: float64

In [22]:
X_new = df[['wmc', 'cbo', 'rfc', 'ce', 'npm', 'loc', 'max_cc']]
X_new

     wmc  cbo  rfc  ce  npm  loc  max_cc
0      4    3   12   1    4   99       3
1      2    0    3   0    2    6       1
2      8    6   22   3    8  176       5
3      8    7   24   6    8  179       7
4     10   34   13   2    9   28       1
..   ...  ...  ...  ..  ...  ...     ...
130    1    2    3   1    0    7       0
131    2    3   16   3    1   51       2
132    5    3   11   2    4   37       1
133    7    2   26   2    2  131       2
134    2    4    6   4    1   14       1

[135 rows x 7 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [24]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  1.0
Recall :  0.36363636363636365
F1 Score :  0.5333333333333333
AUC :  0.6818181818181819

### Support Vector Machine

In [25]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.6829268292682927
Precision :  0.3333333333333333
Recall :  0.18181818181818182
F1 Score :  0.23529411764705885
AUC :  0.5242424242424243

### KNeighborsClassifier

In [26]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [27]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.8
Recall :  0.36363636363636365
F1 Score :  0.5000000000000001
AUC :  0.6651515151515153

# INFORMATION GAIN 10

In [28]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.12331099, 0.06652348, 0.0063327 , 0.09702753, 0.08704546,
       0.10123074, 0.08723994, 0.06403975, 0.16394022, 0.11774803,
       0.05346128, 0.05869476, 0.0406227 , 0.0413341 , 0.17191805,
       0.05233753, 0.        , 0.        , 0.10704604, 0.07148267])

In [29]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [30]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.123311
1      dit  0.066523
2      noc  0.006333
3      cbo  0.097028
4      rfc  0.087045
5     lcom  0.101231
6       ca  0.087240
7       ce  0.064040
8      npm  0.163940
9    lcom3  0.117748
10     loc  0.053461
11     dam  0.058695
12     moa  0.040623
13     mfa  0.041334
14     cam  0.171918
15      ic  0.052338
16     cbm  0.000000
17     amc  0.000000
18  max_cc  0.107046
19  avg_cc  0.071483

In [31]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
14     cam  0.171918
8      npm  0.163940
0      wmc  0.123311
9    lcom3  0.117748
18  max_cc  0.107046
5     lcom  0.101231
3      cbo  0.097028
6       ca  0.087240
4      rfc  0.087045
19  avg_cc  0.071483

In [32]:
FS = list(temp_sort['col'][:10])
FS

['cam', 'npm', 'wmc', 'lcom3', 'max_cc', 'lcom', 'cbo', 'ca', 'rfc', 'avg_cc']

In [33]:
X_new = df[FS]
X_new

          cam  npm  wmc     lcom3  max_cc  lcom  cbo  ca  rfc  avg_cc
0    0.357143    4    4  2.000000       3     6    3   2   12   1.000
1    0.500000    2    2  2.000000       1     1    0   0    3   0.500
2    0.406250    8    8  0.142857       5     0    6   3   22   3.125
3    0.333333    8    8  0.936508       7    12    7   1   24   2.250
4    0.407407    9   10  1.000000       1    45   34  32   13   0.800
..        ...  ...  ...       ...     ...   ...  ...  ..  ...     ...
130  1.000000    0    1  2.000000       0     0    2   1    3   0.000
131  0.666667    1    2  0.000000       2     0    3   1   16   1.000
132  0.533333    4    5  0.250000       1     0    3   1   11   0.800
133  0.277778    2    7  0.666667       2    17    2   0   26   1.000
134  0.750000    1    2  2.000000       1     1    4   1    6   0.500

[135 rows x 10 columns]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [35]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.7142857142857143
Recall :  0.45454545454545453
F1 Score :  0.5555555555555556
AUC :  0.693939393939394

### Support Vector Machine

In [36]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7560975609756098
Precision :  1.0
Recall :  0.09090909090909091
F1 Score :  0.16666666666666669
AUC :  0.5454545454545454

### KNeighborsClassifier

In [37]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7560975609756098
Precision :  1.0
Recall :  0.09090909090909091
F1 Score :  0.16666666666666669
AUC :  0.5454545454545454

### Gaussian Naive Bayes

In [38]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  1.0
Recall :  0.2727272727272727
F1 Score :  0.42857142857142855
AUC :  0.6363636363636364

# INFORMATION GAIN 15

In [39]:
from sklearn.feature_selection import mutual_info_classif
gain = mutual_info_classif(X,Y)
gain

array([0.16849644, 0.        , 0.        , 0.08857374, 0.09447929,
       0.10371073, 0.07824497, 0.06415052, 0.1516392 , 0.10555475,
       0.05836806, 0.03526682, 0.        , 0.04305798, 0.18234882,
       0.03554395, 0.02761696, 0.        , 0.05491404, 0.08894307])

In [40]:
col_list = X.columns
col_list

Index(['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3',
       'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc',
       'avg_cc'],
      dtype='object')

In [41]:
temp = pd.DataFrame(list(zip(col_list, gain)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.168496
1      dit  0.000000
2      noc  0.000000
3      cbo  0.088574
4      rfc  0.094479
5     lcom  0.103711
6       ca  0.078245
7       ce  0.064151
8      npm  0.151639
9    lcom3  0.105555
10     loc  0.058368
11     dam  0.035267
12     moa  0.000000
13     mfa  0.043058
14     cam  0.182349
15      ic  0.035544
16     cbm  0.027617
17     amc  0.000000
18  max_cc  0.054914
19  avg_cc  0.088943

In [42]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:15]

       col     score
14     cam  0.182349
0      wmc  0.168496
8      npm  0.151639
9    lcom3  0.105555
5     lcom  0.103711
4      rfc  0.094479
19  avg_cc  0.088943
3      cbo  0.088574
6       ca  0.078245
7       ce  0.064151
10     loc  0.058368
18  max_cc  0.054914
13     mfa  0.043058
15      ic  0.035544
11     dam  0.035267

In [43]:
FS = list(temp_sort['col'][:15])
FS

['cam',
 'wmc',
 'npm',
 'lcom3',
 'lcom',
 'rfc',
 'avg_cc',
 'cbo',
 'ca',
 'ce',
 'loc',
 'max_cc',
 'mfa',
 'ic',
 'dam']

In [44]:
X_new = df[FS]
X_new

,cam,wmc,npm,lcom3,lcom,rfc,avg_cc,cbo,ca,ce,loc,max_cc,mfa,ic,dam
0,0.357143,4,4,2.000000,6,12,1.000,3,2,1,99,3,0.953488,1,0.000000
1,0.500000,2,2,2.000000,1,3,0.500,0,0,0,6,1,0.000000,0,0.000000
2,0.406250,8,8,0.142857,0,22,3.125,6,3,3,176,5,0.000000,0,1.000000
3,0.333333,8,8,0.936508,12,24,2.250,7,1,6,179,7,0.533333,0,0.555556
4,0.407407,10,9,1.000000,45,13,0.800,34,32,2,28,1,0.000000,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,1.000000,1,0,2.000000,0,3,0.000,2,1,1,7,0,1.000000,0,0.000000
131,0.666667,2,1,0.000000,0,16,1.000,3,1,3,51,2,0.983871,0,0.000000
132,0.533333,5,4,0.250000,0,11,0.800,3,1,2,37,1,0.800000,1,0.000000
133,0.277778,7,2,0.666667,17,26,1.000,2,0,2,131,2,0.000000,0,0.000000
134,0.750000,2,1,2.000000,1,6,0.500,4,1,4,14,1,0.984848,1,0.000000

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [46]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.8
Recall :  0.36363636363636365
F1 Score :  0.5000000000000001
AUC :  0.6651515151515153

### Support Vector Machine

In [47]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [48]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [49]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8536585365853658
Precision :  1.0
Recall :  0.45454545454545453
F1 Score :  0.625
AUC :  0.7272727272727273

# FISHER SCORE

In [50]:
FScore = []

for m in  range(len(col_list)):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        FScore.append(inter_class / intra_class)

FScore

[0.3105372203222329,
 0.006581651154357531,
 0.005246919620110584,
 0.31153121020021546,
 0.2556983555377707,
 0.09310488602910025,
 0.1724336459365908,
 0.23386235119573767,
 0.2532274773841133,
 0.006695634114944451,
 0.2608218201973696,
 0.04272858825834226,
 0.03571795570925816,
 0.0007151935364265742,
 0.07998390768797763,
 0.01629881749008155,
 0.018300582594582716,
 0.025510307823691233,
 0.2240010566820572,
 0.1824887289655018]

In [51]:
temp = pd.DataFrame(list(zip(col_list, FScore)), columns =['col', 'score']) 
temp

       col     score
0      wmc  0.310537
1      dit  0.006582
2      noc  0.005247
3      cbo  0.311531
4      rfc  0.255698
5     lcom  0.093105
6       ca  0.172434
7       ce  0.233862
8      npm  0.253227
9    lcom3  0.006696
10     loc  0.260822
11     dam  0.042729
12     moa  0.035718
13     mfa  0.000715
14     cam  0.079984
15      ic  0.016299
16     cbm  0.018301
17     amc  0.025510
18  max_cc  0.224001
19  avg_cc  0.182489

In [52]:
temp_sort = temp.sort_values(['score'], ascending=False)
temp_sort[:10]

       col     score
3      cbo  0.311531
0      wmc  0.310537
10     loc  0.260822
4      rfc  0.255698
8      npm  0.253227
7       ce  0.233862
18  max_cc  0.224001
19  avg_cc  0.182489
6       ca  0.172434
5     lcom  0.093105

In [53]:
FS = list(temp_sort['col'][:10])
FS

['cbo', 'wmc', 'loc', 'rfc', 'npm', 'ce', 'max_cc', 'avg_cc', 'ca', 'lcom']

In [54]:
X_new = df[FS]
X_new

     cbo  wmc  loc  rfc  npm  ce  max_cc  avg_cc  ca  lcom
0      3    4   99   12    4   1       3   1.000   2     6
1      0    2    6    3    2   0       1   0.500   0     1
2      6    8  176   22    8   3       5   3.125   3     0
3      7    8  179   24    8   6       7   2.250   1    12
4     34   10   28   13    9   2       1   0.800  32    45
..   ...  ...  ...  ...  ...  ..     ...     ...  ..   ...
130    2    1    7    3    0   1       0   0.000   1     0
131    3    2   51   16    1   3       2   1.000   1     0
132    3    5   37   11    4   2       1   0.800   1     0
133    2    7  131   26    2   2       2   1.000   0    17
134    4    2   14    6    1   4       1   0.500   1     1

[135 rows x 10 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [56]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7804878048780488
Precision :  0.75
Recall :  0.2727272727272727
F1 Score :  0.39999999999999997
AUC :  0.6196969696969696

### Support Vector Machine

In [57]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [58]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [59]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8536585365853658
Precision :  1.0
Recall :  0.45454545454545453
F1 Score :  0.625
AUC :  0.7272727272727273

# SVM RFE 10

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [61]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=10)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [62]:
X_train = X_train.loc[:, rfe.support_]
X_train

     wmc  cbo  rfc  lcom  ce  loc       dam       cam        amc  avg_cc
114    2    2   16     1   2  100  0.000000  0.750000  49.000000  1.5000
51     8    0   10    28   0   21  0.000000  0.468750   1.625000  0.8750
47     5    2   18     8   1   88  0.500000  0.450000  15.800000  0.8000
4     10   34   13    45   2   28  0.000000  0.407407   1.600000  0.8000
89     8   15   41     8  14  691  0.461538  0.375000  82.125000  6.2500
..   ...  ...  ...   ...  ..  ...       ...       ...        ...     ...
39     7    5   35    15   5  179  0.000000  0.250000  24.000000  1.0000
91     2    2    4     1   1    8  0.000000  0.750000   3.000000  0.5000
31     7   28   16     9   1   91  0.750000  0.333333  11.428571  1.2857
40    20   17   46    58   8  413  0.666667  0.237500  19.200000  1.6500
83     4    3    8     0   2   38  1.000000  0.400000   8.250000  0.7500

[94 rows x 10 columns]

In [63]:
X_test = X_test.loc[:, rfe.support_]
X_test

     wmc  cbo  rfc  lcom  ce  loc       dam       cam         amc  avg_cc
118    4    2    9     0   1   47  0.250000  0.555556    9.750000  1.2500
20     5    1    7     8   0   22  1.000000  0.750000    3.200000  0.6000
3      8    7   24    12   6  179  0.555556  0.333333   20.250000  2.2500
110    4    3   10     0   2   37  0.000000  0.583333    8.000000  0.7500
92     9    4   37     8   4  314  0.000000  0.218750   32.555556  2.0000
10     6    3    9     9   2   44  0.000000  0.458333    5.833333  1.1667
77     3    9   10     0   1   49  0.000000  1.000000   14.333333  0.6667
101    2    4   15     0   3   77  0.000000  0.666667   35.500000  1.0000
18     9    3   34    34   3  167  0.000000  0.175000   17.333333  1.4444
93     5    3   18     4   3   76  0.000000  0.360000   14.000000  1.2000
2      8    6   22     0   3  176  1.000000  0.406250   20.875000  3.1250
28    10   40   13    15   0  169  0.000000  0.333333   14.600000  2.1000
108    2    4    4     1   2   10  0.000000  0.750000    4.000000  0.5000
53     9   22    9    36   4    9  0.000000  0.259259    0.000000  1.0000
50     0    2    0     0   1    0  0.000000  0.000000    0.000000  0.0000
104    5    8   44     8   7  289  0.000000  0.300000   56.000000  1.0000
61     7    4   32    17   4  155  0.000000  0.277778   20.857143  1.0000
124    8    6   30    22   6  324  0.000000  0.285714   38.250000  2.0000
16     6    3   25    13   3  202  0.000000  0.277778   32.333333  1.3333
44    10    6   33    33   6  321  0.600000  0.325000   30.600000  1.7000
7      5    1   14     8   1   45  0.000000  0.333333    7.600000  0.6000
30     6    7   21     0   2  274  0.200000  0.466667   43.000000  2.8333
54     4    2    9     0   1   62  0.000000  0.555556   13.000000  1.7500
120    3    1    7     1   0   20  1.000000  0.444444    5.333333  0.6667
5     12   10   35    24  10  531  0.064516  0.366667   40.666667  5.0833
9      3    0   14     3   0  133  0.000000  0.333333   43.333333  1.6667
81     1    8    1     0   0    1  0.000000  1.000000    0.000000  1.0000
97     4    6   20     0   5   77  0.000000  0.625000   17.000000  1.5000
111   12    9   39    14   9  174  0.000000  0.375000   13.000000  1.3333
76     5    8    6    10   2   13  0.000000  0.466667    0.800000  0.8000
24    12   12   41     0   2  275  0.000000  0.090909   21.666667  2.2500
67     4    2    5     6   2   12  0.000000  0.500000    2.000000  0.7500
46     2    3   22     1   2  128  0.000000  0.750000   63.000000  2.5000
119    0    0    0     0   0    7  0.000000  0.000000    0.000000  0.0000
126    6    3    8    15   3   34  0.000000  0.500000    4.333333  0.8333
100    5    8   26    10   8  508  0.000000  0.266667  100.600000  1.4000
34     4    0   15     6   0   73  0.000000  0.333333   17.250000  0.7500
80     7    3   25    17   3  105  0.000000  0.277778   13.571429  1.1429
133    7    2   26    17   2  131  0.000000  0.277778   17.428571  1.0000
109    4    3   10     0   2   41  0.000000  0.500000    8.750000  0.7500
122    9   13   18    30   4  114  0.625000  0.518519   10.777778  1.2222

### RandomForest

In [64]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7804878048780488
Precision :  1.0
Recall :  0.18181818181818182
F1 Score :  0.3076923076923077
AUC :  0.5909090909090909

### Support Vector Machine

In [65]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [66]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [67]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7317073170731707
Precision :  0.5
Recall :  0.18181818181818182
F1 Score :  0.26666666666666666
AUC :  0.5575757575757576

# SVM RFE 15

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=23)

In [69]:
from sklearn.feature_selection import RFE
rec_model = RandomForestClassifier()

rfe = RFE(rec_model, n_features_to_select=15)
rfe.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [70]:
X_train = X_train.loc[:, rfe.support_]
X_train

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,cam,cbm,amc,max_cc,avg_cc
114,2,2,16,1,0,2,2,2.000000,100,0.000000,0.750000,0,49.000000,3,1.5000
51,8,0,10,28,0,0,8,2.000000,21,0.000000,0.468750,2,1.625000,1,0.8750
47,5,2,18,8,1,1,5,0.750000,88,0.500000,0.450000,2,15.800000,1,0.8000
4,10,34,13,45,32,2,9,1.000000,28,0.000000,0.407407,0,1.600000,1,0.8000
89,8,15,41,8,4,14,2,0.956044,691,0.461538,0.375000,0,82.125000,21,6.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,7,5,35,15,0,5,2,0.750000,179,0.000000,0.250000,0,24.000000,2,1.0000
91,2,2,4,1,1,1,1,2.000000,8,0.000000,0.750000,0,3.000000,1,0.5000
31,7,28,16,9,28,1,6,1.000000,91,0.750000,0.333333,0,11.428571,3,1.2857
40,20,17,46,58,9,8,15,0.649123,413,0.666667,0.237500,3,19.200000,7,1.6500
83,4,3,8,0,1,2,4,0.333333,38,1.000000,0.400000,2,8.250000,1,0.7500

In [71]:
X_test = X_test.loc[:, rfe.support_]
X_test

,wmc,cbo,rfc,lcom,ca,ce,npm,lcom3,loc,dam,cam,cbm,amc,max_cc,avg_cc
118,4,2,9,0,1,1,2,0.916667,47,0.250000,0.555556,0,9.750000,3,1.2500
20,5,1,7,8,1,0,3,0.750000,22,1.000000,0.750000,0,3.200000,1,0.6000
3,8,7,24,12,1,6,8,0.936508,179,0.555556,0.333333,0,20.250000,7,2.2500
110,4,3,10,0,1,2,3,0.000000,37,0.000000,0.583333,0,8.000000,1,0.7500
92,9,4,37,8,0,4,7,0.822917,314,0.000000,0.218750,0,32.555556,7,2.0000
10,6,3,9,9,1,2,6,0.866667,44,0.000000,0.458333,0,5.833333,2,1.1667
77,3,9,10,0,8,1,1,0.000000,49,0.000000,1.000000,0,14.333333,1,0.6667
101,2,4,15,0,1,3,2,0.250000,77,0.000000,0.666667,0,35.500000,2,1.0000
18,9,3,34,34,0,3,2,0.875000,167,0.000000,0.175000,0,17.333333,3,1.4444
93,5,3,18,4,0,3,3,0.500000,76,0.000000,0.360000,7,14.000000,4,1.2000
2,8,6,22,0,3,3,8,0.142857,176,1.000000,0.406250,0,20.875000,5,3.1250
28,10,40,13,15,40,0,8,0.811966,169,0.000000,0.333333,0,14.600000,7,2.1000
108,2,4,4,1,2,2,1,2.000000,10,0.000000,0.750000,0,4.000000,1,0.5000
53,9,22,9,36,18,4,9,2.000000,9,0.000000,0.259259,0,0.000000,1,1.0000
50,0,2,0,0,1,1,0,2.000000,0,0.000000,0.000000,0,0.000000,0,0.0000
104,5,8,44,8,3,7,3,0.875000,289,0.000000,0.300000,0,56.000000,3,1.0000
61,7,4,32,17,0,4,2,0.666667,155,0.000000,0.277778,0,20.857143,2,1.0000
124,8,6,30,22,0,6,2,0.942857,324,0.000000,0.285714,0,38.250000,5,2.0000
16,6,3,25,13,0,3,2,0.700000,202,0.000000,0.277778,0,32.333333,2,1.3333
44,10,6,33,33,0,6,9,0.933333,321,0.600000,0.325000,1,30.600000,5,1.7000
7,5,1,14,8,0,1,2,0.875000,45,0.000000,0.333333,0,7.600000,1,0.6000
30,6,7,21,0,5,2,5,0.900000,274,0.200000,0.466667,0,43.000000,5,2.8333
54,4,2,9,0,1,1,2,1.000000,62,0.000000,0.555556,1,13.000000,4,1.7500
120,3,1,7,1,1,0,3,0.500000,20,1.000000,0.444444,3,5.333333,1,0.6667
5,12,10,35,24,0,10,11,0.994135,531,0.064516,0.366667,4,40.666667,23,5.0833
9,3,0,14,3,0,0,2,2.000000,133,0.000000,0.333333,0,43.333333,4,1.6667
81,1,8,1,0,8,0,1,2.000000,1,0.000000,1.000000,0,0.000000,1,1.0000
97,4,6,20,0,2,5,4,1.066667,77,0.000000,0.625000,4,17.000000,3,1.5000
111,12,9,39,14,0,9,12,0.863636,174,0.000000,0.375000,3,13.000000,4,1.3333
76,5,8,6,10,6,2,5,1.250000,13,0.000000,0.466667,0,0.800000,1,0.8000
24,12,12,41,0,10,2,9,0.666667,275,0.000000,0.090909,0,21.666667,6,2.2500
67,4,2,5,6,0,2,4,2.000000,12,0.000000,0.500000,0,2.000000,1,0.7500
46,2,3,22,1,1,2,2,2.000000,128,0.000000,0.750000,0,63.000000,5,2.5000
119,0,0,0,0,0,0,0,2.000000,7,0.000000,0.000000,0,0.000000,0,0.0000
126,6,3,8,15,0,3,6,1.000000,34,0.000000,0.500000,1,4.333333,2,0.8333
100,5,8,26,10,0,8,2,2.000000,508,0.000000,0.266667,0,100.600000,3,1.4000
34,4,0,15,6,0,0,4,2.000000,73,0.000000,0.333333,0,17.250000,1,0.7500
80,7,3,25,17,0,3,2,0.833333,105,0.000000,0.277778,0,13.571429,2,1.1429
133,7,2,26,17,0,2,2,0.666667,131,0.000000,0.277778,0,17.428571,2,1.0000
109,4,3,10,0,1,2,4,0.500000,41,0.000000,0.500000,2,8.750000,1,0.7500
122,9,13,18,30,9,4,8,0.937500,114,0.625000,0.518519,0,10.777778,3,1.2222

### RandomForest

In [72]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  1.0
Recall :  0.36363636363636365
F1 Score :  0.5333333333333333
AUC :  0.6818181818181819

### Support Vector Machine

In [73]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [74]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [75]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  1.0
Recall :  0.36363636363636365
F1 Score :  0.5333333333333333
AUC :  0.6818181818181819

# MRMR 10

In [76]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [77]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [78]:
K = 10

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [79]:
selected

['cbo', 'amc', 'npm', 'max_cc', 'wmc', 'ce', 'ca', 'loc', 'rfc', 'avg_cc']

In [80]:
X_new = X[selected]
X_new

     cbo        amc  npm  max_cc  wmc  ce  ca  loc  rfc  avg_cc
0      3  23.750000    4       3    4   1   2   99   12   1.000
1      0   2.000000    2       1    2   0   0    6    3   0.500
2      6  20.875000    8       5    8   3   3  176   22   3.125
3      7  20.250000    8       7    8   6   1  179   24   2.250
4     34   1.600000    9       1   10   2  32   28   13   0.800
..   ...        ...  ...     ...  ...  ..  ..  ...  ...     ...
130    2   6.000000    0       0    1   1   1    7    3   0.000
131    3  23.500000    1       2    2   3   1   51   16   1.000
132    3   6.200000    4       1    5   2   1   37   11   0.800
133    2  17.428571    2       2    7   2   0  131   26   1.000
134    4   6.000000    1       1    2   4   1   14    6   0.500

[135 rows x 10 columns]

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [82]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  0.8333333333333334
Recall :  0.45454545454545453
F1 Score :  0.5882352941176471
AUC :  0.7106060606060606

### Support Vector Machine

In [83]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [84]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [85]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8292682926829268
Precision :  0.8333333333333334
Recall :  0.45454545454545453
F1 Score :  0.5882352941176471
AUC :  0.7106060606060606

# MRMR 15

In [86]:
from sklearn.feature_selection import f_regression

F = pd.Series(f_regression(X, Y)[0], index = X.columns)
corr = X.corr().abs().clip(.00001)

In [87]:
selected = []
feat_score = []
not_selected = list(X.columns)

In [88]:
K = 15

for i in range(K):
    
    # compute FCQ score for all the (currently) excluded features (this is Formula 2)
    score = F.loc[not_selected] / corr.loc[not_selected, selected].mean(axis = 1).fillna(.00001)
    
    # find best feature, add it to selected and remove it from not_selected
    best = score.index[score.argmax()]
    selected.append(best)
    feat_score.append(score[best])
    not_selected.remove(best)

In [89]:
selected

['cbo',
 'amc',
 'npm',
 'max_cc',
 'wmc',
 'ce',
 'ca',
 'loc',
 'rfc',
 'avg_cc',
 'dam',
 'cam',
 'lcom',
 'cbm',
 'moa']

In [90]:
X_new = X[selected]
X_new

,cbo,amc,npm,max_cc,wmc,ce,ca,loc,rfc,avg_cc,dam,cam,lcom,cbm,moa
0,3,23.750000,4,3,4,1,2,99,12,1.000,0.000000,0.357143,6,3,0
1,0,2.000000,2,1,2,0,0,6,3,0.500,0.000000,0.500000,1,0,0
2,6,20.875000,8,5,8,3,3,176,22,3.125,1.000000,0.406250,0,0,0
3,7,20.250000,8,7,8,6,1,179,24,2.250,0.555556,0.333333,12,0,0
4,34,1.600000,9,1,10,2,32,28,13,0.800,0.000000,0.407407,45,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,2,6.000000,0,0,1,1,1,7,3,0.000,0.000000,1.000000,0,0,0
131,3,23.500000,1,2,2,3,1,51,16,1.000,0.000000,0.666667,0,0,1
132,3,6.200000,4,1,5,2,1,37,11,0.800,0.000000,0.533333,0,1,1
133,2,17.428571,2,2,7,2,0,131,26,1.000,0.000000,0.277778,17,0,1
134,4,6.000000,1,1,2,4,1,14,6,0.500,0.000000,0.750000,1,1,0

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [92]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.7142857142857143
Recall :  0.45454545454545453
F1 Score :  0.5555555555555556
AUC :  0.693939393939394

### KNeighborsClassifier

In [93]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Support Vector Machine

In [94]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### KNeighborsClassifier

In [95]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7073170731707317
Precision :  0.4
Recall :  0.18181818181818182
F1 Score :  0.25000000000000006
AUC :  0.5409090909090909

### Gaussian Naive Bayes

In [96]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.8
Recall :  0.36363636363636365
F1 Score :  0.5000000000000001
AUC :  0.6651515151515153

# MRMR HFS

In [97]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d + (d*(d-1)*(sum(red_FF)/len(red_FF))))**(1/2)
            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [98]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['cbo', 'cbm']

In [99]:
X_new = X[FS]

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [101]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  0.8
Recall :  0.36363636363636365
F1 Score :  0.5000000000000001
AUC :  0.6651515151515153

### Support Vector Machine

In [102]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7804878048780488
Precision :  1.0
Recall :  0.18181818181818182
F1 Score :  0.3076923076923077
AUC :  0.5909090909090909

### KNeighborsClassifier

In [103]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  1.0
Recall :  0.2727272727272727
F1 Score :  0.42857142857142855
AUC :  0.6363636363636364

### Gaussian Naive Bayes

In [104]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7560975609756098
Precision :  0.6
Recall :  0.2727272727272727
F1 Score :  0.37499999999999994
AUC :  0.603030303030303

# HFS NEW

In [105]:
def HSF(df, df_train):
    
    from copy import deepcopy
    col_list = list(df_train.columns)
    print(col_list)
    d = df_train.shape[1]
    SF = []
    merit = [0 for i in range(d)]
    merit_archive = [0 for i in range(d)]
    Total_FS = [0 for i in range(d)]

    rel_CF = RHFS(df, d, col_list)

    max_value = max(rel_CF)
    Feature_max_index = rel_CF.index(max_value)

    n = 0

    SF.append(Feature_max_index)

    merit_archive[n] = deepcopy(max_value)

    Total_FS[n] = deepcopy(SF)

    while n < d-1:

        for i in range(d):

            red_FF = SHFS(SF, df_train, i, col_list,d)

            top = (d + d*(sum(rel_CF)/len(rel_CF)))
            bottom = (d - (sum(red_FF)/len(red_FF)))**(1/2)

            merit[i] = top/bottom

        for val in SF:
            merit[val] = -9999999

        max_value = max(merit)
        Feature_max_index = merit.index(max_value)

        if Feature_max_index not in SF:
            SF.append(Feature_max_index)

        n += 1
        
        Total_FS[n] = deepcopy(SF)

        merit_archive[n] = max_value

    index_val = merit_archive.index(max(merit_archive))

    Feature_subset = Total_FS[index_val]

    subset_list = []

    for val in Feature_subset:
        subset_list.append(col_list[val])
    return subset_list


def RHFS(df, d, col_list):
    rel_CF = [0 for i in range(d)]
    count = 0

    igain = IG(X,df['class'])

    for m in  range(d):
        mu = df[col_list[m]].mean()

        n_1 = df[df['class'] == 0].count()[1]
        mu_1 = df[col_list[m]][df['class'] == 0].mean()
        var_1 = df[col_list[m]][df['class'] == 0].var()

        n_2 = df[df['class'] == 1].count()[1]
        mu_2 = df[col_list[m]][df['class'] == 1].mean()
        var_2 = df[col_list[m]][df['class'] == 1].var()

        inter_class = n_1*(mu_1-mu)**2 + n_2*(mu_2-mu)**2
        intra_class = (n_1-1)*var_1 + (n_2-1)*var_2

        fscore = inter_class / intra_class

        rel_CF[count] = (1/2)*(fscore + igain[m])
        count += 1
    
    return rel_CF

        
        

def IG(col_1, col_2):
    from sklearn.feature_selection import mutual_info_classif
    gain = mutual_info_classif(col_1,col_2)
    return gain   

def relief(col_1,col_2):
    pass



def SHFS(SF, df_train, i, col_list,d):
    from itertools import combinations
    from copy import deepcopy
    red_FF = []
    temp_SF = deepcopy(SF)
    if i not in SF:
        temp_SF.append(i)
        P_pairs = list(combinations(temp_SF,2))
        for pair in P_pairs:

            ied_value = (IED(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            pc_value = (PC(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2
            cs_value = (CS(df_train[col_list[pair[0]]],df_train[col_list[pair[1]]]))**2

            red_FF.append((1/3)*(ied_value + pc_value + cs_value))
            # red_FF.append((1/2)*(pc_value + cs_value))
    else:
        red_FF = [0]
    return red_FF

def IED(col_1, col_2):
    import numpy as np
    dist = np.linalg.norm(col_1 - col_2)
    return 1/dist

def PC(col_1, col_2):
    from scipy.stats import pearsonr
    corr, _ = pearsonr(col_1 , col_2)
    return corr

def CS(col_1, col_2):
    from scipy import spatial
    similarity = 1 - spatial.distance.cosine(col_1, col_2)
    return similarity

In [106]:
FS = HSF(df, X)
FS

['wmc', 'dit', 'noc', 'cbo', 'rfc', 'lcom', 'ca', 'ce', 'npm', 'lcom3', 'loc', 'dam', 'moa', 'mfa', 'cam', 'ic', 'cbm', 'amc', 'max_cc', 'avg_cc']

['wmc', 'npm']

In [107]:
X_new = X[FS]

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.3,random_state=23)

### RandomForest

In [109]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7560975609756098
Precision :  0.6
Recall :  0.2727272727272727
F1 Score :  0.37499999999999994
AUC :  0.603030303030303

### Support Vector Machine

In [110]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  1.0
Recall :  0.2727272727272727
F1 Score :  0.42857142857142855
AUC :  0.6363636363636364

### KNeighborsClassifier

In [111]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7560975609756098
Precision :  0.5714285714285714
Recall :  0.36363636363636365
F1 Score :  0.4444444444444444
AUC :  0.631818181818182

### Gaussian Naive Bayes

In [112]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8048780487804879
Precision :  1.0
Recall :  0.2727272727272727
F1 Score :  0.42857142857142855
AUC :  0.6363636363636364